### ISSUE TITLE
GTX 1080 low perfomance

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/nheqminer#105]
GTX 1080 - 29 Sols/s
GTX 1070 - 30 Sols/s
Why 1080 shows such poor results?

**Comment by chronosek** [comment]
GDDR5X (1080) isn't performing as well as GDDR5 (1070) on mining, there are many topics about that

**Comment by Kayfolom** [comment]
> GDDR5X (1080) isn't performing as well as GDDR5 (1070) on mining, there are many topics about that
the question is not about memory types, the question of why GTX 1080 is slower than  GTX 1070

**Comment by buzztiaan** [comment]
eh, he gave you an answer regarding that

**Comment by S74nk0** [comment]
@Kayfolom this is to be expected. GTX 1080 will give worse results than GTX 1070 when mining (this is also the case with Ethereum for example)

**Comment by joseortiz3** [comment]
GTX 1080 should be getting about 20% higher hashrate that 1070 in today's world. Not sure about Nov of 2016, but today the above information is outdated, for what it's worth.

**Comment by buzztiaan** [comment]
Just to compare, today i get on a GTX1060 ;

[INFO] [2018-05-11T08:01:58+02:00] Total 298.28 Sol/s 160.09 Nonce/s
Accepted shares 5594 Rejected shares 44
