### ISSUE TITLE
Please advice

### ISSUE THREAD

**Issue by cryptomonk** [nicehash/nheqminer#11]
`~/nheqminer/build$ make
g++ -c -m64 -pipe -std=gnu++11 -O3 -Wall -W -fPIC -DHAVE_DECL_HTOBE16 -DHAVE_DECL_HTOLE16 -DHAVE_DECL_BE16TOH -DHAVE_DECL_LE16TOH -DHAVE_DECL_HTOBE32 -DHAVE_DECL_HTOLE32 -DHAVE_DECL_BE32TOH -DHAVE_DECL_LE32TOH -DHAVE_DECL_HTOBE64 -DHAVE_DECL_HTOLE64 -DHAVE_DECL_BE64TOH -DHAVE_DECL_LE64TOH -DHAVE_BYTESWAP_H -DHAVE_DECL_BSWAP_16 -DHAVE_DECL_BSWAP_32 -DHAVE_DECL_BSWAP_64 -I../nheqminer -I. -I../nheqminer/3rdparty -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o ../nheqminer/main.cpp
In file included from ../nheqminer/3rdparty/boost/predef/hardware/simd.h:9:0,
                 from ../nheqminer/3rdparty/boost/predef/hardware.h:14,
                 from ../nheqminer/3rdparty/boost/predef.h:20,
                 from ../nheqminer/3rdparty/boost/smart_ptr/detail/yield_k.hpp:28,
                 from ../nheqminer/3rdparty/boost/smart_ptr/detail/spinlock_sync.hpp:18,
                 from ../nheqminer/3rdparty/boost/smart_ptr/detail/spinlock.hpp:50,
                 from ../nheqminer/3rdparty/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from ../nheqminer/3rdparty/boost/smart_ptr/shared_ptr.hpp:35,
                 from ../nheqminer/3rdparty/boost/shared_ptr.hpp:17,
                 from ../nheqminer/3rdparty/boost/signals2/deconstruct.hpp:28,
                 from ../nheqminer/3rdparty/boost/signals2.hpp:15,
                 from ../nheqminer/libstratum/ZcashStratum.h:10,
                 from ../nheqminer/libstratum/StratumClient.h:6,
                 from ../nheqminer/main.cpp:8:
../nheqminer/3rdparty/boost/predef/hardware/simd/x86.h:13:53: fatal error: boost/predef/hardware/simd/x86/versions.h: No such file or directory
compilation terminated.
Makefile:1859: recipe for target 'main.o' failed
make: *** [main.o] Error 1
`

**Comment by S74nk0** [comment]
This is an old build it is not relevant anymore. Use the latest Linux (**work in progress**) branch or master branch
