### ISSUE TITLE
ocl_xpm.lib error windows

### ISSUE THREAD

**Issue by TIKCrazy** [nicehash/nheqminer#110]
Hello. im trying to build last release, but when nheqminer compiling, im getting that error: 
Error	3	error LNK1181: cannot open input file 'ocl_xpm.lib'	E:\Miner\nheqminer\LINK	nheqminer
I dont even needed amd support, i turned off from everywhere ocl_xpm solution, but anyway this error. Can you help me, please?

**Comment by S74nk0** [comment]
Have you removed from **nheqminer** project Properties > Linker > Input > ocl_xpm.lib? Remove that and preprocessor  **USE_OCL_XMP**.

**Comment by TIKCrazy** [comment]
It helps, thanks!

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
