### ISSUE TITLE
Windows Compile Issue

### ISSUE THREAD

**Issue by Eyedol-X** [nicehash/nheqminer#112]
I installed all the required items and downloaded the latest commit. I run the build in VS2013 and it connects to NH but shows 0 I/s and 0 Sols/s on CPU. If I enable GPU it shows xxxx I/s and 0 Sol/s.

Everything I try seems to have no effect.

What am I missing?

**Comment by S74nk0** [comment]
@Eyedol-X NVIDIA GPU?
