### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by updatede** [nicehash/nheqminer#114]
nheqminer_cpu exit with "Illegal instruction" immediately.
os: Debian 8.6.0  cpu: intel E8400

**Comment by buzztiaan** [comment]
thats a 8 year old cpu, you probably need to compile the miner yourself to
match your cpu architecture

**Comment by S74nk0** [comment]
@updatede your CPU has SSE2 so build it without USE_CPU_XENONCAT (AVX1/AVX2) and use USE_CPU_TROMP (SSE2).
