### ISSUE TITLE
Higher CPU than Intel i7 6700 K but still get on 6-7 sol/s

### ISSUE THREAD

**Issue by tjsangariya** [nicehash/nheqminer#115]
Hi,
I have a workstation with this configuration
I have total 10 workstation with this configuration.

BUT I think zcash mining is not properly working on my system.

Operating System is WIN 10 64 BIT with 2 Xeon processor and 32 GB ram with 8Gb AMD GPU
Processors Information

Processor 1 ID = 0
Number of cores 8 (max 16)
Number of threads 16 (max 32)
Name Intel Xeon E5 2650 v2
Codename Ivy Bridge-EP/EX
Specification Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
Package (platform ID) Socket 2011 LGA (0x0)
CPUID 6.E.4
Extended CPUID 6.3E
Core Stepping M0/M1
Technology 22 nm
TDP Limit 95.0 Watts
Tjmax 89.0 °C
Core Speed 2940.2 MHz
Multiplier x Bus Speed 30.0 x 98.0 MHz
Rated Bus speed 3528.3 MHz
Stock frequency 2600 MHz
Instructions sets MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, AES, AVX
L1 Data cache 8 x 32 KBytes, 8-way set associative, 64-byte line size
L1 Instruction cache 8 x 32 KBytes, 8-way set associative, 64-byte line size
L2 cache 8 x 256 KBytes, 8-way set associative, 64-byte line size
L3 cache 20 MBytes, 20-way set associative, 64-byte line size
FID/VID Control yes

Turbo Mode      supported, enabled
Max non-turbo ratio 26x
Max turbo ratio     34x
Max efficiency ratio    12x
Max Power       150 Watts
Min Power       60 Watts
O/C bins        none
Ratio 1 core        34x
Ratio 2 cores       33x
Ratio 3 cores       32x
Ratio 4 cores       31x
Ratio 5 cores       30x
Ratio 6 cores       30x
Ratio 7 cores       30x
Ratio 8 cores       30x
TSC         2600.1 MHz
APERF           3000.0 MHz
MPERF           2599.9 MHz

Temperature 0       45°C (113°F) [0x2C] (Core #0)
Temperature 1       50°C (122°F) [0x27] (Package)
Power 0         59.22 W (Package)
Power 1         46.80 W (IA Cores)
Power 3         12.42 W (Uncore)
Voltage 0       1.00 Volts (VID)

Processor 2 ID = 1
Number of cores 8 (max 16)
Number of threads 16 (max 32)
Name Intel Xeon E5 2650 v2
Codename Ivy Bridge-EP/EX
Specification Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
Package (platform ID) Socket 2011 LGA (0x0)
CPUID 6.E.4
Extended CPUID 6.3E
Core Stepping M0/M1
Technology 22 nm
TDP Limit 95.0 Watts
Tjmax 89.0 °C
Core Speed 2940.2 MHz
Multiplier x Bus Speed 30.0 x 98.0 MHz
Rated Bus speed 3528.3 MHz
Stock frequency 2600 MHz
Instructions sets MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, AES, AVX
L1 Data cache 8 x 32 KBytes, 8-way set associative, 64-byte line size
L1 Instruction cache 8 x 32 KBytes, 8-way set associative, 64-byte line size
L2 cache 8 x 256 KBytes, 8-way set associative, 64-byte line size
L3 cache 20 MBytes, 20-way set associative, 64-byte line size
FID/VID Control yes

Turbo Mode      supported, enabled
Max non-turbo ratio 26x
Max turbo ratio     34x
Max efficiency ratio    12x
Max Power       150 Watts
Min Power       60 Watts
O/C bins        none
Ratio 1 core        34x
Ratio 2 cores       33x
Ratio 3 cores       32x
Ratio 4 cores       31x
Ratio 5 cores       30x
Ratio 6 cores       30x
Ratio 7 cores       30x
Ratio 8 cores       30x
TSC         2600.1 MHz
APERF           3000.0 MHz
MPERF           2599.8 MHz

Temperature 0       52°C (125°F) [0x25] (Core #0)
Temperature 17      55°C (131°F) [0x22] (Package)
Power 16            56.86 W (Package)
Power 17            44.53 W (IA Cores)
Power 19            12.33 W (Uncore)
Voltage 16      1.00 Volts (VID)

But get only 6-7 h/s for zcash nicehashv0.3a
WHY?????????????

**Comment by tjsangariya** [comment]
Any one help ??

**Comment by tjsangariya** [comment]
dual cpu in my workstation with Intel Xeon E5 2650 v2Intel Xeon E5 2650 v2
I get 500h/s on XMR mining with these CPU's
but on Zcash :( :(

**Comment by S74nk0** [comment]
Those numbers are extremely low for a CPU like that. Does the miner say it is using AVX when running? Did you change -t paramters?

**Comment by tjsangariya** [comment]
low ......................   Xeon E5 2650 V2 with 16 cores and having 2 CPU in one system
I use -t parameters with more options 
-t 6,-t16 and others but still not getting much hashes

**Comment by tjsangariya** [comment]
Intel i7 6700K having only 8 cores ??

**Comment by tjsangariya** [comment]
![ipmsgclip_s_1478161731_0](https://cloud.githubusercontent.com/assets/16588559/19959566/bdfa1648-a1cd-11e6-87fc-35a062631a66.png)

**Comment by tjsangariya** [comment]
Please see image ??

**Comment by tjsangariya** [comment]
ANY ONE THEIR FOR HELP

**Comment by buzztiaan** [comment]
how long did you leave it running? it needs like 15-30 minutes to stabilize speed

**Comment by tjsangariya** [comment]
Only 4-5 minutes running but not in upper image it is only starting of miner.
You mean to say CPU will take time to stable .
OKAY I'll start running it and contact again after one hours......

THANK YOU :)

**Comment by buzztiaan** [comment]
cool, i'll be watching github

**Comment by tjsangariya** [comment]
Hi Again ,
after running half an hour it show like this
what is the meaning of 
2016-11-03 15:19:54.734446][0x000047b8]: Speed [300 sec]: 5.58667 I/s, 10.5333 Sols/s
[2016-11-03 15:20:05.060819][0x000047b8]: Speed [300 sec]: 5.58 I/s, 10.43 Sols/s
[2016-11-03 15:20:15.362824][0x000047b8]: Speed [300 sec]: 5.58333 I/s, 10.47 Sols/s
[2016-11-03 15:20:25.713438][0x000047b8]: Speed [300 sec]: 5.56667 I/s, 10.3867 Sols/s
[2016-11-03 15:20:26.240409][0x00003ef0]: stratum | Submitting share #29, nonce 07000000000000000000000000000000000000000000000000000022
[2016-11-03 15:20:26.512115][0x000042b0]: stratum | Accepted share #29
[2016-11-03 15:20:27.073641][0x00004184]: stratum | Submitting share #30, nonce 05000000000000000000000000000000000000000000000000000021
[2016-11-03 15:20:27.378639][0x000042b0]: stratum | Accepted share #30
[2016-11-03 15:20:36.023100][0x000047b8]: Speed [

![ipmsgclip_s_1478166615_0](https://cloud.githubusercontent.com/assets/16588559/19961528/179c41a2-a1d9-11e6-9886-d612c04b09a1.png)

**Comment by buzztiaan** [comment]
ok, 

a) can you post your command line plz 
b) can you try closing those ~15 programs you are running while mining, and tell me speed again after ~30 minutes?

**Comment by tjsangariya** [comment]
I use these on 3 systems
nheqminer.exe -u tjsangariya.tej -p x -t 16 -e 1
nheqminer.exe -u tjsangariya.tej -p x -t 16 -e 0
nheqminer.exe -u tjsangariya.tej -p x -t 16 

I am a programmer so I'll work together with this but my other 2 system are free for this and they also have same output

**Comment by buzztiaan** [comment]
a) you should be using AVX2 -not- AVX1 and -not- SSE2 , if you just remove -e it should autodetect the right one to use (provided you compiled the right one)

b) dont use 16 on 16cores HT , as mentioned in other bugs -and- documention, you should start at the number of -actual cores- for -t (in your case -t 8) and then start upping , -t 9 , -t 10 , -t 11 , to find which -exact- number of threads suits your 16core HT (no, its NOT 16, it never is)

**Comment by tjsangariya** [comment]
Please see these 2 images having 2 physical processors and their configurations
and suggest the value of -t ??

![ipmsgclip_s_1478169850_0](https://cloud.githubusercontent.com/assets/16588559/19963037/9e4c60b8-a1e0-11e6-90c6-d7f6318ec43a.png)

![ipmsgclip_s_1478169818_0](https://cloud.githubusercontent.com/assets/16588559/19963024/8a917a36-a1e0-11e6-8904-ee1db62fc1e7.png)

**Comment by tjsangariya** [comment]
Hello buzztiaan
Please reply my 10 workstation waiting for mining on Zcash ??

**Comment by buzztiaan** [comment]
i already told you

> dont use 16 on 16cores HT , as mentioned in other bugs -and- documention, you should start at the number of -actual cores- for -t (in your case -t 8) and then start upping , -t 9 , -t 10 , -t 11 , to find which -exact- number of threads suits your 16core HT (no, its NOT 16, it never is)

**Comment by buzztiaan** [comment]
this isnt 'general help' this is for CODE issues, move to irc channel on freenode, #zcash-mining

**Comment by tjsangariya** [comment]
:( :(
