### ISSUE TITLE
Cannot build on CentOS6

### ISSUE THREAD

**Issue by susloparovdenis** [nicehash/nheqminer#116]
I have issues with boost. 
I have older version of boost:
BOOST_ROOT = /public/apps/boost/1.58.0/gcc.5.2.0
LD_LIBRARY_PATH =  /public/apps/boost/1.58.0/gcc.5.2.0/lib

I can see that boost headers from newer version are included in this repo, so I added 
`export CPATH=$CPATH:~/nheqminer/3rdparty/include/`
But I still get this:

> [ 88%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/denis/ZEC/nheqminer/cpu_xenoncat/xenoncat.cpp.o
> make[2]: *** No rule to make target `/usr/lib64/lib64/libboost_date_time-mt.so.5', needed by `nheqminer_cpu'.  Stop.
> make[1]: *** [CMakeFiles/nheqminer_cpu.dir/all] Error 2
> make: *** [all] Error 2

**Comment by susloparovdenis** [comment]
Sol

**Comment by susloparovdenis** [comment]
cmake -DBoost_NO_BOOST_CMAKE=BOOL:ON . helped

**Comment by buzztiaan** [comment]
thanks for the fix \o
