### ISSUE TITLE
50% Less Sol/s than other Miners

### ISSUE THREAD

**Issue by Kaakati** [nicehash/nheqminer#118]
nheqminer makes less Sol/s than other miners that are using SILENTARMY kernel.

**Comment by bigrck64** [comment]
Please Nicehash, update the kernel for AMD gpu to unleash their power :+1:

**Comment by S74nk0** [comment]
checkout this branch [silentarmy](https://github.com/nicehash/nheqminer/tree/Windows_silentarmy). It is called **Windows_silentarmy** branch but has also Linux cmake files. It is very much a work in progress, seems stable with single and multiple GPUs and it should be about 3 times faster than the current release. User feedback would be appreciated since there might be some hidden issues. So please test this build

**Comment by xlh2esw** [comment]
@S74nk0 I get `make` error on Ubuntu 16.04 LTS x86_64 using **Windows_silentarmy** like you suggested:

```
CMakeFiles/nheqminer_cpu.dir/build.make:230: recipe for target 'CMakeFiles/nheqminer_cpu.dir/home/ubuntu/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o' failed
make[2]: *** [CMakeFiles/nheqminer_cpu.dir/home/ubuntu/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by S74nk0** [comment]
@xlh2esw install the following dependencies:
  - `sudo apt-get install mesa-common-dev`
  - [AMD APP SDK](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/)
  - and make sure you have the [AMD drivers](http://support.amd.com/en-us/download) installed
  - install them to the default paths
  - `cmake -DOPENCL_LIBRARY=/usr/lib/x86_64-linux-gnu/libOpenCL.so -DOPENCL_INCLUDE_DIRECTORY=/opt/AMDAPPSDK-3.0/include` **nheqminer/Linux_cmake/nheqminer_AMD/CMakeLists.txt**
 - make

this should work

**Comment by xlh2esw** [comment]
@S74nk0 I'm CPU mining, not GPU.

**Comment by S74nk0** [comment]
@xlh2esw sorry. **silentarmy** is the optimized OpenCL kernel code primary focused on AMD. For CPU use the existing instructions. CPU_XENONCAT should give very good results fot CPU mining

**Comment by xlh2esw** [comment]
@S74nk0 yes, getting ~150 Sols/s now on one machine with CPU_XENONCAT. Thank you for your efforts!

**Comment by Kaakati** [comment]
I'm using Windows

**Comment by bpvarsity** [comment]
@xlh2esw what CPU do you have that can make you get 150 Sols/s?

**Comment by Eyedol-X** [comment]
I installed all the required items and downloaded the latest silent_army commit. I run the build in VS2013 and it connects to NH but shows 0 I/s and 0 Sols/s on CPU. If I enable GPU it shows xxxx I/s and 0 Sol/s.

Everything I try seems to have no effect.

What am I missing?

**Comment by Kaakati** [comment]
Version 0.4a is out, It fixed the issue.
