### ISSUE TITLE
windows build doesn't work 

### ISSUE THREAD

**Issue by IlyaParachuter** [nicehash/nheqminer#12]
There used boost from the folder '3rdparty', and
also included following headers:
# include <boost / log / *

which just absent in 3rdparty folder. What to do?

**Comment by tupieurods** [comment]
Until nicehash will fix it, you can get this dirs from somewhere else. Or jsut use git checkout and get this folders from an earlier versions, where this folders were presented

**Comment by zenbooster** [comment]
I took 3rdparty / boost from this commit:
3466b69ec4cd62346d177fda8d93da011d456f02 (added cmake file (Linux only for now))
and I got the following error:

nheqminer-master\nheqminer\3rdparty\boost/type_traits/common_type.hpp(43): fatal error C1001: An internal error has occurred in the compiler.

I use Microsoft Visual Studio Ultimate 2013
Version 12.0.21005.1 REL
and platform toolset:
Visual C++ Compiler Nov 2013 CTP (CTP_Nov2013)

**Comment by tupieurods** [comment]
Can't help with this one. Never faced with it. Try to run Clean adn Rebuild.

**Comment by zenbooster** [comment]
After installing update 5 (https://www.microsoft.com/en-us/download/details.aspx?id=48129) build was successful!
