### ISSUE TITLE
-l usa option usa:2142

### ISSUE THREAD

**Issue by CryptoRob** [nicehash/nheqminer#123]
"Connecting to stratum server usa:2142
resolve: No such host is known"

batch file command:
nheqminer.exe -l usa -u <t address> -t 2 -op 1

Was running the nheqminer_zcash.exe (no longer maintaining separate exe's?) via v0.3a using the same command, which connected to stratum.usa.zcash.nicehash.com:3357 without issue.

**Comment by nicehashdev** [comment]
nheqminer.exe -l stratum.usa.zcash.nicehash.com:3357 -u <t address> -t 2 -op1

**Comment by Eyedol-X** [comment]
You have to update your command as the -l allows you to pick any server/pool.

**Comment by CryptoRob** [comment]
Disregard - this works:
-l stratum.usa.zcash.nicehash.com:3357

**Comment by CryptoRob** [comment]
Thanks Eyedol-X, just worked it out. Apologies for the mis-report.

**Comment by CryptoRob** [comment]
Thanks nicehashdev, appreciate the help...

**Comment by Desilator** [comment]
Hey Thanks for the heads upon this.  Worked great!  Any reason your command line says -op1?  I thought AMD was -od and NVIDIA was -cd.  I'm not sure if you just made a type or if I'm missing something else now.  This is the .bat I'm running

nheqminer.exe -l stratum.usa.zcash.nicehash.com:3357 -u -t 6 -cd 0 1

I'm running two GTX970s and a i5-6600 3.3 which is pulling about 65+ Sols/s at the time of this post.

**Comment by nicehashdev** [comment]
-op tells you which platform. Your cards may sometimes be on another platform and not 0 (default). -op 1 tells miner to search for GPUs on platform 1. Use -oi to get informed about devices and platforms.
