### ISSUE TITLE
новая версия не работает майнер закрывается видеокарты amd r9 380

### ISSUE THREAD

**Issue by gennadiv** [nicehash/nheqminer#125]
на процессорах работает

**Comment by foxwarernd** [comment]
укажите командную строку которую используете для запуска

**Comment by gennadiv** [comment]
nheqminer - equihash.usa.nicehash.com:3357 -u 1P2PuynmmqU2gKsmHo75RQ2y8SD56NuG1f.gennadiv.3 -p x -t 0 -od 0 1 2

**Comment by gennadiv** [comment]
всё запустил - пришлось удалить opencl -работает теперь хорошо

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
