### ISSUE TITLE
Dual CPU

### ISSUE THREAD

**Issue by phatbasstrd** [nicehash/nheqminer#126]
Miner only recognizes one of my 2 iCore CPU's.

**Comment by italy2010** [comment]
i have same problem.

**Comment by nicehashdev** [comment]
If you have two CPUs in your machine, we suggest you to run two miner instances and assign each one own NODE. Or properly assign affinities to run one instance on one cpu and another instance on another cpu.

**Comment by italy2010** [comment]
how i can  assign each one own NODE?

**Comment by faddat** [comment]
I've got the same question.  I use systemd unit files to set up my stuff.
