### ISSUE TITLE
GeForce GT 710M a cuda 2.1 card, 2.2k I/s 0 S/s it needs to be fixed

### ISSUE THREAD

**Issue by twatsnn** [nicehash/nheqminer#130]
im encountering this problem,it needs to be fixed

**Comment by nicehashdev** [comment]
-cv 1

Also experiement with -cb and -ct

**Comment by twatsnn** [comment]
i did it experimented with almost all ower cb and ct values

also using -cv 1

**Comment by twatsnn** [comment]
i did it experimented with almost all lower cb and ct values

also using -cv 1

2016-11-04 10:45 GMT+02:00 nicehashdev <notifications@github.com>:

**Comment by twatsnn** [comment]
problem still exists .. any help ?
