### ISSUE TITLE
Linux build issue (both CUDA & CPU)

### ISSUE THREAD

**Issue by m00r3ik** [nicehash/nheqminer#132]
[compile_error.txt](https://github.com/nicehash/nheqminer/files/571227/compile_error.txt)
[environment.txt](https://github.com/nicehash/nheqminer/files/571236/environment.txt)

**Comment by S74nk0** [comment]
Latest commit should fix it. Close thread if it works.

**Comment by S74nk0** [comment]
Latest commit fixes this. Closing issue.
