### ISSUE TITLE
0.4a Multi-Gpu Open CL crash

### ISSUE THREAD

**Issue by Eyedol-X** [nicehash/nheqminer#135]
I'm still doing some testing but in ~12 Hours the only system I have that is still running on Windows 10 x64 is a system 1x RX480.

2 Systems with 4 RX480s and 1 System with 4x R9390s both crashed at least twice before I switched them back to 0.3a which works fine and has been for days.

I was using the silent_army kernal in 0.4a.

I'm going to try individual instances of 0.4a from seperate directories and see if that has an effect on my multi-gpu systems. IE: 1 Directory, 1 GPU Instance

Will report back with results. 

I will also try the XMP kernal in 0.4a and see if that has any effect.

**Comment by Eyedol-X** [comment]
Looks like using individual instances may work, Comment from bigrck64 in this thread - https://github.com/nicehash/nheqminer/issues/122

**Comment by S74nk0** [comment]
@Eyedol-X how often does it crash? You can use [NHM](https://github.com/nicehash/NiceHashMiner) this will handle starting and stopping the miner automatically (extra options do not work at the moment).

**Comment by Eyedol-X** [comment]
@S74nk0 It seems to be random and I can confirm it is not just limited to AMD GPU's -- I had a system crash this morning with 2 1070's -- If I create separate directories for each instance and on the 1st instance use the CPU+GPU 0 and the 2nd instance use NOCPU+GPU 1, etc it seems to be stable. My system with 1 RX480 has been running strong since yesterday

**Comment by S74nk0** [comment]
`2 1070's` you are using CUDA for this or OpenCL? Sinlge device mining works stable but multiple devices cause problems?

**Comment by Eyedol-X** [comment]
Cuda for the 1070's -- with 2 of them running in same instance 0.4a crashed, 0.3a never did

**Comment by maztheman** [comment]
try -cv 1 to force the old implementation.

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
