### ISSUE TITLE
LOW PRIORITY: ocl_xml.cpp(207), missing a parameter to sprintf

### ISSUE THREAD

**Issue by maztheman** [nicehash/nheqminer#137]
This is probably not the right way of getting this fixed but I converted the project to vs 2015, and im getting this warning.  no biggie, wont cause a crash I don't think but its worth noting.

1>ocl_xmp.cpp(207): warning C4473: 'sprintf' : not enough arguments passed for format string

**Comment by S74nk0** [comment]
Fixed
