### ISSUE TITLE
OCL_XMP for Ubuntu 14.04?

### ISSUE THREAD

**Issue by Enzo-life** [nicehash/nheqminer#139]
Is there any work for 14.04 or should we move to 16.04?

**Comment by S74nk0** [comment]
@Enzo-life all steps should be same. We just didn't test it on Ubuntu 14.04

**Comment by Enzo-life** [comment]
I've got such error messages while compiling:
> /home/user/nheqminer/ocl_device_utils/opencl.cpp: In function 'bool clInitialize(int, std::vector<_cl_device_id*>&)':
/home/user/nheqminer/ocl_device_utils/opencl.cpp:39:64: warning: format '%s' expects argument of type 'char*', but argument 2 has type 'int' [-Wformat=]
     printf("<error> platform %s not exists\n", requiredPlatform);
                                                                ^
/home/user/nheqminer/ocl_device_utils/opencl.cpp: In function 'bool clCompileKernel(cl_context, cl_device_id, const char*, const std::vector<const char*>&, const char*, cl_int*, _cl_program**)':
/home/user/nheqminer/ocl_device_utils/opencl.cpp:87:16: error: expected type-specifier
       } catch (std::system_error& e) {
                ^
/home/user/nheqminer/ocl_device_utils/opencl.cpp:87:33: error: expected unqualified-id before '&' token
       } catch (std::system_error& e) {
                                 ^
/home/user/nheqminer/ocl_device_utils/opencl.cpp:87:33: error: expected ')' before '&' token
/home/user/nheqminer/ocl_device_utils/opencl.cpp:87:33: error: expected '{' before '&' token
/home/user/nheqminer/ocl_device_utils/opencl.cpp:87:35: error: 'e' was not declared in this scope
       } catch (std::system_error& e) {
                                   ^
/home/user/nheqminer/ocl_device_utils/opencl.cpp:87:36: error: expected ';' before ')' token
       } catch (std::system_error& e) {
                                    ^
make[2]: *** [CMakeFiles/nheqminer_AMD.dir/home/user/nheqminer/ocl_device_utils/opencl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/nheqminer_AMD.dir/all] Error 2
make: *** [all] Error 2


So i don't know, maybe there are some absend dependencies in 14.04.

**Comment by maztheman** [comment]
its a bug youll have to change %s to %d

**Comment by Enzo-life** [comment]
I don't think it will work, it's just a message about "requiredPlatform", but there are more errors below.

**Comment by Enzo-life** [comment]
Yes, i've got same errors, except sprintf argument type.

**Comment by maztheman** [comment]
ok try adding: 
`#include <system_error>`
to the top of the file

**Comment by maztheman** [comment]
im trying to replicate it now..

**Comment by Enzo-life** [comment]
Included:

> /home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp: In member function 'bool OclContext::init(cl_device_id, unsigned int, unsigned int)':
/home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp:91:10: warning: '_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)' is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1359) [-Wdeprecated-declarations]
  queue = clCreateCommandQueue(_context, dev, 0, &error);
          ^
/home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp:91:55: warning: '_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)' is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1359) [-Wdeprecated-declarations]
  queue = clCreateCommandQueue(_context, dev, 0, &error);
                                                       ^
/home/user/nheqminer/ocl_device_utils/opencl.cpp: In function 'bool clCompileKernel(cl_context, cl_device_id, const char*, const std::vector<const char*>&, const char*, cl_int*, _cl_program**)':
/home/user/nheqminer/ocl_device_utils/opencl.cpp:89:59: error: cannot pass objects of non-trivially-copyable type 'std::string {aka class std::basic_string<char>}' through '...'
         fprintf(stderr, "<error> %s\n", e.code().message());
                                                           ^
/home/user/nheqminer/ocl_device_utils/opencl.cpp:89:59: warning: format '%s' expects argument of type 'char*', but argument 3 has type 'std::string {aka std::basic_string<char>}' [-Wformat=]

**Comment by maztheman** [comment]
now youll have to change the line 89 to this:
fprintf(stderr, " %s\n", e.code().message().c_str()

**Comment by maztheman** [comment]
its possible these commits happend after the release..

**Comment by Enzo-life** [comment]
Hmmmm, i don't know how and why, but now miner has compiled successfully. There are some errors with level "deprecated" and no any output from e.code().message().c_str().

**Comment by maztheman** [comment]
I'm glad it worked out for you.  hopefully a real developer will show up here and know the exactly right thing to do. :)  What i showed you was just a temp fix..

**Comment by Enzo-life** [comment]
Thanks for trying to help :) Compiled miner just aborts with segmentation fault. 
And so interersting thing... If i just update printf command, compiling process shows errors that i showed first time.
But if i have included <system_error>, compiling process shows another errors (deprecated):

> [ 85%] Building CXX object CMakeFiles/nheqminer_AMD.dir/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp.o
/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp:27:24: warning: ignoring attributes on template argument '__blake2b_state' [enabled by default]
  clBuffer<blake2b_state> blake2bState;
                        ^
/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp: In member function 'bool MinerInstance::init(cl_context, cl_program, cl_device_id, unsigned int, unsigned int)':
/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp:59:10: warning: '_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)' is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1359) [-Wdeprecated-declarations]
  queue = clCreateCommandQueue(context, dev, 0, &error);
          ^
/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp:59:54: warning: '_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)' is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1359) [-Wdeprecated-declarations]
  queue = clCreateCommandQueue(context, dev, 0, &error);
                                                      ^
/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp: In static member function 'static void ocl_xmp::start(ocl_xmp&)':
/home/user/nheqminer/ocl_xpm/ocl_xmp.cpp:207:61: warning: format '%u' expects a matching 'unsigned int' argument [-Wformat=]
   sprintf(kernelName, "equiw200k9_gpu%u_%u.bin", (unsigned)i);
                                                             ^
[ 90%] Building CXX object CMakeFiles/nheqminer_AMD.dir/home/user/nheqminer/cpu_tromp/blake2/blake2bx.cpp.o
[ 95%] Building CXX object CMakeFiles/nheqminer_AMD.dir/home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp.o
/home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp: In member function 'bool OclContext::init(cl_device_id, unsigned int, unsigned int)':
/home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp:91:10: warning: '_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)' is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1359) [-Wdeprecated-declarations]
  queue = clCreateCommandQueue(_context, dev, 0, &error);
          ^
/home/user/nheqminer/ocl_silentarmy/ocl_silentarmy.cpp:91:55: warning: '_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)' is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1359) [-Wdeprecated-declarations]
  queue = clCreateCommandQueue(_context, dev, 0, &error);
                                                       ^
[100%] Building CXX object CMakeFiles/nheqminer_AMD.dir/home/user/nheqminer/ocl_silentarmy/sa_blake.cpp.o
Linking CXX executable nheqminer_AMD

But compiled miner got segmentation fault when trying to mine.

Since i am a programmer, i can't get why there is such difference between including error class.

**Comment by maztheman** [comment]
std::string s;
printf("%s", s) doesn't compile because %s expects const char *, which std::string is not, however std::string::c_str() will give printf what it needs.

Also I think for whatever reason std::system_error is not being included earlier.

Did you copy the Amd binaries like in the readme?

can you add the command line argument "-d 0" and show me the output of the benchmark? 

eg. ./nheqminer_AMD -d 0 -t 0 -od 0 -b

**Comment by Enzo-life** [comment]
I've installed AMD APP SDK like in the readme.

> # ./nheqminer_AMD -d 0 -t 0 -od 0 -b

        ==================== www.nicehash.com ====================
                Equihash CPU&GPU Miner for NiceHash v0.4a
        Thanks to Zcash developers for providing base of the code.
               Special thanks to tromp, xenoncat, mbevand
                     and eXtremal-ik7 for providing
              optimized CPU, CUDA and AMD equihash solvers.
        ==================== www.nicehash.com ====================

Setting log level to 0
[21:51:35][0x00007fd0b58ac780] Using SSE2: YES
[21:51:35][0x00007fd0b58ac780] Using AVX: NO
[21:51:35][0x00007fd0b58ac780] Using AVX2: NO
[21:51:35][0x00007fd0b58ac780] Benchmarking OPENCL worker (OCL_SILENTARMY) GPU_ID(0)
<info> found 5 devices
Using device 0 as GPU 0
<info> compiling ...
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted (core dumped)

Now i'm going to sleep, thank you for help.

**Comment by maztheman** [comment]
Well the only thing I can think of is a OpenCL file is missing:

./zcash/gpu/kernel.cl

This is relative path where ever the executable is
When the "kernel.cl" file is missing it does not create a binary file that the benchmark needs to run..
I wish I could help more...

**Comment by Enzo-life** [comment]
As i see, https://github.com/nicehash/nheqminer/tree/Linux/ocl_xpm/zcash/gpu here is no kernel.cl. Should it be in this directory?

**Comment by maztheman** [comment]
No it is in the silent army project.

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
