### ISSUE TITLE
0 / i/s , 0 Sols/s then -t 0  -od 0 on windows

### ISSUE THREAD

**Issue by thesios** [nicehash/nheqminer#141]
0 / i/s , 0 Sols/s then -t 0  -cd 0 on windows 

but -od 0 -t 1 
work fine

**Comment by twatsnn** [comment]
im cuda 2.1 gpu user (geforce 710m) using -cv 1 parameter and already experimented with lower -cb -ct values but still 0 solve any help ?

**Comment by adykoff** [comment]
My system is Core i5 Processor with a frequency of 1.8 Hertz nvideo GT 750m and it works on nheqminer v.02a suprnova. 10 sols

**Comment by S74nk0** [comment]
The new binaries use older CUDA SDK 7.5 and should work. Try the new version and reopen if the problem is still present
