### ISSUE TITLE
-cv 1 does not work on Nvidia GT 750M (0 Sols/s) on v0.4b

### ISSUE THREAD

**Issue by moisesmcardona** [nicehash/nheqminer#144]
Hi,

Using the -cv 1 command doesn't work on the Nvidia Geforce GT 750M. My GPU usage is just 3 to 8%, and it still shows 0 Sols/s. I also tried using the tuning commands -ct and -cb without success. I'm using the v0.4b version.

Thanks,
Moises

**Comment by jddebug** [comment]
I followed the post by chronosek in the following thread and it worked for me on my 760. I was having the same problem as you.

https://github.com/nicehash/nheqminer/issues/57 

http://chronx.pl/cuda/cuda_tromp_0.3a.zip

**Comment by Lunaari** [comment]
jddebug's solution doesn't work for me. It may be that the cuda_tromp dlls need to be compiled for 0.4am, but I'm just throwing out guesses.

System: 477K @ 5.7 and 780ti classified.

**Comment by jddebug** [comment]
Lunaari, I'm sorry I didn't specify, I used them in place of the files in 0.3a. I did try them in 0.4a and they worked WITHOUT the -cv 1 but didn't with -cv 1 added.

**Comment by Lunaari** [comment]
My 780ti is trying to use CUDA-TROMP-75 not CUDA-TROMP with 0.4a. I'll see if I can find that DLL recompiled for my machine.

**Comment by chronosek** [comment]
you could try 0.4b version compiled by me (i do not know if work for cc2.x cards yet)
http://chronx.pl/cuda/cuda_tromp_0.4b.zip

**Comment by moisesmcardona** [comment]
Yup, it is working now :) Thank you!! Those are the DLLs that needs to be bundled in the next release :)

**Comment by Lunaari** [comment]
Ahhhh chronosek you're the best. Thanks m8!

**Comment by moisesmcardona** [comment]
Ok, on an unrelated question, but why is the CPU much faster than the GPU itself?

**Comment by chronosek** [comment]
zcash (zec) is a new coin, it will mature with time... I have i7-4790k and gtx980, cpu - 28 sol/s, gpu - 25 sol/s , but there are some miners (only for linux) what perform better on gpu, i hope developers will improve nheqminer too

**Comment by jddebug** [comment]
chronosek. Thanks. donation on the way.

**Comment by chronosek** [comment]
Thanks.

**Comment by montvid** [comment]
Nvidia geforce 740m does not work with the -cv 1 parameter but works at 2.5 sol without it. Compiled with COMPUTE=35 for my card on ubuntu 16.04 so I guess I don't need this parameter?
