### ISSUE TITLE
Location toggle not working

### ISSUE THREAD

**Issue by Bschmitz99** [nicehash/nheqminer#149]
When launching version 0.4b using the "-l {usa, jp, hk, eu} command it no longer recognizes those as a location for the stratum server. It is also trying to connect on port 2142. I was able to get it to work by entering "-l equihash.usa.nicehash.com:3357" hoping we can get it fixed to a simple toggle of usa, eu, jp, or hk again.
![capture](https://cloud.githubusercontent.com/assets/6267549/20022728/ea81654a-a2a9-11e6-9c8d-6d7dda753942.PNG)

**Comment by maztheman** [comment]
you now have to put in the full address:

eg. equihash.usa.nicehash.com:3357

**Comment by Bschmitz99** [comment]
why switch to that? it is more complicated for people to know. And if that
is the case then that should be added to the release notes listing the
address so people can just copy and paste them.


Thank you
Brandan Schmitz

Lifeguard & WSI
Certified Apple Developer
Eagle Scout & SPL of Troop 507
Admin of https://www.ighfdexplorers.com

**Comment by maztheman** [comment]
You are not wrong, for sure.  They could use a switch to do the same thing as the old "-l" switch.

**Comment by Bschmitz99** [comment]
that would be good, still have the switch and add the function for the full
address if it is meant to allow for mining on other pools in the future.


Thank you
Brandan Schmitz

Lifeguard & WSI
Certified Apple Developer
Eagle Scout & SPL of Troop 507
Admin of https://www.ighfdexplorers.com

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
