### ISSUE TITLE
Build error AMD debian 8.6

### ISSUE THREAD

**Issue by rlong011** [nicehash/nheqminer#150]
I have a debian 8.6 x86_64.  I have AMD cards with the fglrx_15.302-0ubuntu1_amd64_ub_14.01 driver and AMD-APP-SDK-v3.0.130.136-GA-linux64 installed.  When I bulid I get the following error:

/root/nheqminer/ocl_device_utils/opencl.cpp: In function ‘bool clCompileKernel(cl_context, cl_device_id, const char*, const std::vector<const char*>&, const char*, cl_int*, _cl_program**)’:
/root/nheqminer/ocl_device_utils/opencl.cpp:87:21: error: ‘system_error’ in namespace ‘std’ does not name a type
       } catch (std::system_error& e) {
                     ^
/root/nheqminer/ocl_device_utils/opencl.cpp:88:41: error: ‘e’ was not declared in this scope
         fprintf(stderr, "<error> %s\n", e.code().message());
                                         ^
CMakeFiles/nheqminer_AMD.dir/build.make:399: recipe for target 'CMakeFiles/nheqminer_AMD.dir/root/nheqminer/ocl_device_utils/opencl.cpp.o' failed
make[2]: *** [CMakeFiles/nheqminer_AMD.dir/root/nheqminer/ocl_device_utils/opencl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/nheqminer_AMD.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_AMD.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

I'm not sure what to do.

**Comment by maztheman** [comment]
same issue as:
#139

**Comment by maztheman** [comment]
modify nheqminer/ocl_device_utils/opencl.cpp by adding
`#include <system_error>` under the other includes
and modify `fprintf(stderr, "<error> %s\n", e.code().message());` to be `fprintf(stderr, "<error> %s\n", e.code().message().c_str());`

**Comment by rlong011** [comment]
Thanks, sorry I did not find #139
