### ISSUE TITLE
AMD on debian 8.6 getting  terminate called after throwing an instance of 'std::ios_base::failure'

### ISSUE THREAD

**Issue by rlong011** [nicehash/nheqminer#152]
**When running the following and when trying to mine**

root@debian86:~# /root/nheqminer/Linux_cmake/nheqminer_AMD/nheqminer_AMD -d 0 -t 0 -od 0 -b -ov 0

**I get**
	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.4a
	Thanks to Zcash developers for providing base of the code.
	       Special thanks to tromp, xenoncat, mbevand 
	             and eXtremal-ik7 for providing 
	      optimized CPU, CUDA and AMD equihash solvers.
	==================== www.nicehash.com ====================

Setting log level to 0
[18:56:15][0x00007fca26cd2740] Using SSE2: YES
[18:56:15][0x00007fca26cd2740] Using AVX: YES
[18:56:15][0x00007fca26cd2740] Using AVX2: NO
[18:56:15][0x00007fca26cd2740] Benchmarking OPENCL worker (OCL_SILENTARMY) GPU_ID(0)
<info> found 3 devices
Using device 0 as GPU 0
<info> compiling ...
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted

**Comment by maztheman** [comment]
Is there a zcash subfolder where you are running the miner?

**Comment by rlong011** [comment]
I'm running it from /root/nheqminer/Linux_cmake/nheqminer_AMD/ which is the only place the executable is.  Is there another folder should run from, I have a /root/.zcash and a /root/zcash which I built zcash from.

**Comment by maztheman** [comment]
ok try the command -oi   when i do that it doesnt even detect my amd gpu

**Comment by rlong011** [comment]
==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.4a
	Thanks to Zcash developers for providing base of the code.
	       Special thanks to tromp, xenoncat, mbevand 
	             and eXtremal-ik7 for providing 
	      optimized CPU, CUDA and AMD equihash solvers.
	==================== www.nicehash.com ====================

Number of OpenCL devices found: 3
	Platform: AMD Accelerated Parallel Processing | PlatformNum: 0
		Devices: 
			#0 Tahiti | GPU
			#1 Tahiti | GPU
			#2 Tahiti | GPU

**Comment by maztheman** [comment]
OK so now I need to know of there is any .bin files that are being created? In my local build I put in a bunch of debug output if any open CL stuff fails...let me know

**Comment by rlong011** [comment]
Here are the *.bin files
/root/nheqminer/3rdparty/kernel_RX4xx_windows_16.7/equiw200k9.bin
/root/nheqminer/3rdparty/kernel_R92xx_linux_14.4/equiw200k9.bin
/root/nheqminer/3rdparty/amd_bins_windows/equiw200k9.bin
/root/nheqminer/3rdparty/amd_bins_linux/equiw200k9.bin
/root/nheqminer/cpu_xenoncat/Linux/demo/input.bin
/root/nheqminer/cpu_xenoncat/Linux/asm/t2.bin
/root/nheqminer/Linux_cmake/nheqminer_AMD/equiw200k9.bin
/root/nheqminer/Linux_cmake/nheqminer_AMD/CMakeFiles/3.0.2/CMakeDetermineCompilerABI_C.bin
/root/nheqminer/Linux_cmake/nheqminer_AMD/CMakeFiles/3.0.2/CMakeDetermineCompilerABI_CXX.bin
/root/nheqminer/nheqminer/silentarmy_gpu0.bin

**Comment by rlong011** [comment]
OK, ran out of ~/nheqminer/Linux_cmake/nheqminer_AMD/zcash/gpu where the kernel.cl and other files are and got:

Setting log level to 2
[23:24:50][0x00007f8039465740] Using SSE2: YES
[23:24:50][0x00007f8039465740] Using AVX: YES
[23:24:50][0x00007f8039465740] Using AVX2: NO
[23:24:50][0x00007f8036d37700] stratum | Starting miner
[23:24:50][0x00007f8036536700] miner#0 | Starting thread #0 (OCL_SILENTARMY) GPU_ID(0)
[23:24:50][0x00007f8035d35700] miner#1 | Starting thread #1 (OCL_SILENTARMY) GPU_ID(1)
[23:24:50][0x00007f8036d37700] stratum | Connecting to stratum server usa:2142
[23:24:50][0x00007f8035534700] miner#2 | Starting thread #2 (OCL_SILENTARMY) GPU_ID(2)
<info> found 3 devices
<info> found 3 devices
Using device 2 as GPU 0
<info> compiling ...
<info> found 3 devices
Using device 1 as GPU 0
Using device 0 as GPU 0
<info> compiling ...
<info> compiling ...
terminate called recursively
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  Aborted

**Comment by maztheman** [comment]
OK, now you are getting same issue as other people on here saying multi gpu isn't working.  Hmm.

**Comment by rlong011** [comment]
it happens with 1 or 3

**Comment by maztheman** [comment]
Well it also looks like you are still going -l usa which won't work anymore
You have to put in url and port.  The read me was updated

**Comment by rlong011** [comment]
I'd changed that previously, but to no avail:

root@debian86:~/nheqminer/Linux_cmake/nheqminer_AMD/zcash/gpu# /root/nheqminer/Linux_cmake/nheqminer_AMD/nheqminer_AMD -l zec-us-west1.nanopool.org:6666 -u t1NKLdSNTXYiyGgo6BVp6rVXBTWzC8S3RPv -t 0 -op 0 -od 0

	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.4a
	Thanks to Zcash developers for providing base of the code.
	       Special thanks to tromp, xenoncat, mbevand 
	             and eXtremal-ik7 for providing 
	      optimized CPU, CUDA and AMD equihash solvers.
	==================== www.nicehash.com ====================

Setting log level to 2
[23:44:24][0x00007f9d0c845740] Using SSE2: YES
[23:44:24][0x00007f9d0c845740] Using AVX: YES
[23:44:24][0x00007f9d0c845740] Using AVX2: NO
[23:44:24][0x00007f9d0a117700] stratum | Starting miner
[23:44:24][0x00007f9d0a117700] stratum | Connecting to stratum server zec-us-west1.nanopool.org:6666
[23:44:24][0x00007f9d09916700] miner#0 | Starting thread #0 (OCL_SILENTARMY) GPU_ID(0)
[23:44:24][0x00007f9d0a117700] stratum | Connected!
[23:44:25][0x00007f9d0a117700] stratum | Subscribed to stratum server
[23:44:25][0x00007f9d0a117700] miner | Extranonce is 0a260200000000005f7ff5d137a1db7b
[23:44:25][0x00007f9d0a117700] stratum | Target set to 00147ae100000000000000000000000000000000000000000000000000000000
[23:44:25][0x00007f9d0a117700] stratum | Authorized worker t1NKLdSNTXYiyGgo6BVp6rVXBTWzC8S3RPv
[23:44:25][0x00007f9d0a117700] stratum | Received new job #1478321012
<info> found 3 devices
Using device 0 as GPU 0
<info> compiling ...
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted

**Comment by maztheman** [comment]
Heh, I'm not sure how linux works but I think you are in the wrong directory. You are in the gpu folder you need to be up two levels.  It uses relative paths to load kernel.cl

**Comment by rlong011** [comment]
It is now working with multi gpus all is well

**Comment by rlong011** [comment]
Thank you very much for your help

**Comment by maztheman** [comment]
No problem.  I'm glad it's working for you!

**Comment by maztheman** [comment]
I would propose to the developers to add file detection and report missing files to the users :-)
