### ISSUE TITLE
stupid question on mining and economics 

### ISSUE THREAD

**Issue by thesios** [nicehash/nheqminer#153]
Hi 

first stupid question are ALL the miners working on the same block at the same time ?  or is it pool dependent  and one pool is working on a subset of blocks different from the other pools.

**Comment by thesios** [comment]
second question is 

If I run multiple instances of the miner do i want to run on different pools

**Comment by zerf2004** [comment]
Just adding a question on this "issue" since it really isn't an issue but didn't want to create another one for my question. Anyway... How come the new Windows builds don't have the _zcash.exe build anymore? Is that a flag we set now instead? Thanks!

**Comment by michelem09** [comment]
@thesios almost  every pools can set many workers so you can have multiple instances connected to the same pool but with different worker names. For example:

```
nheqminer_cpu -l pool1 -u <wallet-address>.worker1
nheqminer_cpu -l pool1 -u <wallet-address>.worker2
```

and so on.

BTW this is not an issue and you should ask this on a forum not here.
