### ISSUE TITLE
Fail OCL

### ISSUE THREAD

**Issue by bruxo00** [nicehash/nheqminer#156]
Hey! So, I'm having an issue with your awesome miner.

I'm doing a mining manager software for my rigs and everytime I open your miner to mine with GPU (-od) from my program, it just starts spamming "Fail ocl". But the WTF thing is, if I open the miner directly from the bat, it works perfectly! How can this be?

(the CPU mining works perfectly too when launched from bat and when launched from my app)

**Testing on my rig with:**

Newest miner version
FX 8350
R9 380X (Radeon Software Version 16.9.2 | Driver Packaging Version 16.40.2311-160916a-307329C)
Windows 10 64 Bits

**Some prints:**

Miner starting perfectly when open directly from .bat:
https://i.gyazo.com/7e93035a9fc3c3bb3e2948616a138ed8.png

Miner starting directly from my C# code:
https://i.gyazo.com/64112dd80bf746ff52774fd9431efc22.png
https://i.gyazo.com/c2fb1a45194584e46c46720dd03e849a.png

 **EDIT:** Didn't noticed the new update. Testing right now.

 **EDIT 2:** No more Fail OCL errors but now the program crashes. Just like before, all good when starting from the bat, crashing when starting from my app. Note that I'm using the exactly same launch params (-od 0 only).

The crash now: 
https://i.gyazo.com/530076ad4a8e1c366ec2dd4cb9ac39b0.png

Then "nheqminer.exe stopped working".

**Comment by maztheman** [comment]
When it goes to open zcash/GPU/kernel.cl
It isn't finding it and is returning a stream error. By the looks of it

**Comment by bruxo00** [comment]
How can I fix that? The files are in the folder...

Thanks for the reply.

**Comment by maztheman** [comment]
They have to be relative to where you are running the program. There are a couple of closed issues ive helped with

**Comment by bruxo00** [comment]
I don't know how I didn't tested this before. If I run my app from the miner folder it starts  perfectly. Thanks! :)
