### ISSUE TITLE
opencl compile error

### ISSUE THREAD

**Issue by updatede** [nicehash/nheqminer#157]
when compile nheqminer_AMD on debian 8.6.0, it reports some errors and warnings.
1. system_error not in std name space. I fixed it by include <system_error>.
2. e.message() error. I fixed it by replacing with e.message().c_str().
3. ignoring attributes on template argument __blacke2b_state. not fixed.
4. clCreateCommandQueue is deprecated. not fixed.

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
