### ISSUE TITLE
Windows Binary How to mine on custom pool and get paid in ZCash?

### ISSUE THREAD

**Issue by basicsk8r13** [nicehash/nheqminer#158]
I want to use my own pool not the nice hash pool.  Is there a way to do this and be paid in ZCash instead of bitcoin?

If so what is the command line arguements to do this?

**Comment by montvid** [comment]
The same arguments as in the nheqminer -l your pool address. I use it for flypool on ubuntu.

**Comment by JelloHuang** [comment]
most pool use stratum protocol default and now  nicehash suport all pool .so u can  use -l to add u pool

**Comment by S74nk0** [comment]
@basicsk8r13 yes read [here](https://github.com/nicehash/nheqminer/issues/179). You can use a pool of your choice
