### ISSUE TITLE
Silentarmy clCreateBuffer (-61)

### ISSUE THREAD

**Issue by updatede** [nicehash/nheqminer#159]
![img_0539](https://cloud.githubusercontent.com/assets/22807434/20029327/1c2b9cde-a384-11e6-830c-f8313c2da64b.JPG)

**Comment by maztheman** [comment]
I get this error when the gpu cannot allocate the 1.748 GB of memory.

**Comment by lolzivkovic** [comment]
Yeah i got the same error on the MSI Radeon HD 7770, i can mine with genoil zec miner just fine. Here i get this error and cannot fix it. This only happens why i try to mine /w silentarmy

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
