### ISSUE TITLE
How to pipe hash rate 

### ISSUE THREAD

**Issue by basicsk8r13** [nicehash/nheqminer#161]
For the Windows binary is there a way to pipe the hash rate my machine is mining at to another program or write it to a file or any other way to get it?

**Comment by maztheman** [comment]
nheqminer.exe -l equihash.usa.nicehash.com:3357 -u <BTC ADDR> -t 4 2> logfile.txt

but this will send all console output, your other program will have to parse it.  If you want only the hash rate then some patches would have to be put in..

**Comment by felixbrucker** [comment]
you can use the api, see #165
