### ISSUE TITLE
CUDA v8 instead of v7.5 

### ISSUE THREAD

**Issue by white-energy** [nicehash/nheqminer#163]
Why not use CUDA 8 instead of 7.5 for NVIDIA cards since it has huge benefits for Pascal GPUs?

> **New in CUDA 8**
> 
>    - Pascal Architecture Support
>    - Enhance performance out-of-the-box on Pascal GPUs
>    - Simplify programming using Unified Memory including support for large datasets, concurrent data access and atomics
>    - Optimize Unified Memory performance using new data migration APIs
>    - Increase throughput at ultra-fast speeds using NVIDIA® NVLINK™, new high-speed interconnect

> **Developer Tools**
>    - Identify latent system-level bottlenecks using critical path analysis
>    - Improve productivity by up to 2x with faster NVCC compile times
>    - Tune OpenACC applications and overall host code using new profiling extensions

> **Libraries**
>    - Accelerate graph analytics algorithms with nvGRAPH
>    - Speed-up Deep Learning applications using native support for FP16 and INT8, support for batch operation in cuBLAS

**Comment by chronosek** [comment]
they use cuda 8.0 for newer and cuda 7.5 for older, you just need use -cv option, but still if someone have problems can try compiled dll by me chronx.pl/cuda/cuda_tromp_0.4b.zip what works 2.x-6.2 for 8.0 and 2.x-5.2 for 7.5... I could provide even for older cards like 1.1+

**Comment by white-energy** [comment]
That is weird cause:
http://i.imgur.com/aetNqef.png
