### ISSUE TITLE
Nheqminer API Documentation

### ISSUE THREAD

**Issue by adambh** [nicehash/nheqminer#165]
So I saw this -a param for connecting to the API using a port...
Any explanations on how to use this?

**Comment by felixbrucker** [comment]
use a socket connection and pack your request with "status", response is json

this is the only supported method right now and only offers a few stats

you can quickly test it by opening a telnet session with something like putty (on windows) and entering "status" (without the quotes)

**Comment by white-energy** [comment]
So I have connected to it through Telnet but unfortunately I wasn't getting what I needed...

> {"method":"status","result":false,"error":"Invalid request."}

**Comment by felixbrucker** [comment]
yes, i noticed this happens for the first request it seems, just try again

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
