### ISSUE TITLE
OpenCL failed

### ISSUE THREAD

**Issue by BrianTheDreamer** [nicehash/nheqminer#169]
Hi,
I have an Alienware Aurora with NVIDIA Titan Z Dual GPU.
I know I'm suppose to use cuda but somehow OpenCL switch gives me better results (~40 sols/s).
I was using this line in v0.3a
`nheqminer.exe -l eu -u [myWalletAddress].OpenCL -t 8 -op 0 -od 0 1`
and its working fine. But in the new version (0.4b), I just changed it to
`nheqminer.exe -l equihash.eu.nicehash.com:3357 -u [myWalletAddress].OpenCL -t 8 -op 0 -od 0 1` and its either just exiting, or giving fail OCL error.

I also noticed the new switches in OpenCL section
-ov, 0 gives `OpenCL error: -1001 at opencl.cpp:14` and -ov 1 gives `fail OCL` error
-ot, Do I have to specify value here, or can I skip this?

I tried copying the OpenCL.dll from v03.a but it makes no difference.
What could be causing OpenCL to fail?

Thanks in advance.

**Comment by maztheman** [comment]
-1001 means that platform does not exist.  Show the output for -oi, please.

**Comment by BrianTheDreamer** [comment]
```

	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.4b
	Thanks to Zcash developers for providing base of the code.
	       Special thanks to tromp, xenoncat, mbevand 
	             and eXtremal-ik7 for providing 
	      optimized CPU, CUDA and AMD equihash solvers.
	==================== www.nicehash.com ====================

Number of OpenCL devices found: 2
	Platform: NVIDIA CUDA | PlatformNum: 0
		Devices: 
			#0 GeForce GTX TITAN Z | GPU
			#1 GeForce GTX TITAN Z | GPU

```

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
