### ISSUE TITLE
binaries for v0.2a but source code for v0.1c

### ISSUE THREAD

**Issue by zenbooster** [nicehash/nheqminer#17]
in releases/Public alpha WIN64 builds (https://github.com/nicehash/nheqminer/releases/tag/0.2a):
binaries for v0.2a but source code for v0.1c.

**Comment by zenbooster** [comment]
In https://github.com/nicehash/nheqminer/blob/0.2a/nheqminer/version.h:
#define STANDALONE_MINER_VERSION	"0.1c"
Why?

**Comment by wintermute0001** [comment]
@S74nk0 @nicehashdev could you please comment to this?  This is pretty important and shouldn't be too hard to fix (right? I'm assuming it's just a commit/merge away...)

**Comment by DavBE** [comment]
Same here. This is really annoying.

**Comment by S74nk0** [comment]
Sources pushed...
