### ISSUE TITLE
nheqminer: command not found

### ISSUE THREAD

**Issue by fr1zzer** [nicehash/nheqminer#170]
root@zerver:~/nheqminer/Linux_cmake/nheqminer_cpu# nheqminer -l equihash.eu.nicehash.com:3357 -u 1HGxquBN2mFadEReDBLhkijBebHkfeq62d -t 2
nheqminer: command not found

I set all the instructions on what to do next? As the console log in the folder with the miner?

**Comment by michelem09** [comment]
You must use `./nheqminer`or you should copy it in your path before you can tun it without `./`

**Comment by maztheman** [comment]
No if you are in nheqminer_cpu folder the program is called ./nheqminer_cpu

**Comment by fr1zzer** [comment]
http://s8.hostingkartinok.com/uploads/images/2016/11/47dcc76ec5bdb4c0347734c62edbb437.png

**Comment by fr1zzer** [comment]
How to use on a VPS ?

**Comment by maztheman** [comment]
root@zerver:~# cd ~/nheqminer/Linux_cmake/nheqminer_cpu && ./nheqminer_cpu -l equihash.eu.nicehash.com:3357 -u 1HGxquBN2mFadEReDBLhkijBebHkfeq62d -t 2
