### ISSUE TITLE
What coin am I mining here?

### ISSUE THREAD

**Issue by owocki** [nicehash/nheqminer#172]
Total n00b question, but I dont see anything in the read me.  Does nicehash mine zcash, or does the system automatically switch me to whatever network is most profitable?

**Comment by ramonhugo** [comment]
**NiceHash** is an algorithm. And actually is just that, a _hash algorithm_.

**ZCash** uses that algorithm, and then to mine **ZCash** you need to use a program that implements that algorithm.

You are not using **nicehash** _per se_, you are using the **miner nheqminer**.

So you can use a miner, with the specific algorithm to solve a specific kind of cryptocoin.
Nicehash does not mine anything, and the nheqminer is used to solve nicehash.
If you want to use a system that chooses the coin you need a pool that do that.

**Comment by HPrivakos** [comment]
The algorithm is **Equihash**, nicehash is just a company for rent hashing power on different algorithms, but they have build one of the better equihash miner: **nhequiminer** (**N**ice**H**ash **Equi**hash **Miner**), it's why a lot of other equihash miner are based on this one.

For the moment, i think ZCash is the only coin using Equihash, you can learn more on the website: [https://z.cash/](https://z.cash/)

**Comment by owocki** [comment]
Thanks ya'll.  this answers my question.

**Comment by S74nk0** [comment]
If you use **nheqminer** with NiceHash service with your Bitcoin address like so **-l equihash.eu.nicehash.com -u BTC_ADDRESS** you will be payed in Bitcoin for renting your hashing power.
But if you want to mine ZCash with it you can mine with your ZCash addres on our pool like so **-l stratum.eu.zcash.nicehash.com -u ZCASH_ADDRESS**. The eu location can be replaced with usa,jp and ch depending depending on your location
