### ISSUE TITLE
Nheqminer and particular OpenCL Linux considerations

### ISSUE THREAD

**Issue by ramonhugo** [nicehash/nheqminer#175]
I'm not sure how to make this work in Linux, particularly on Fedora OS.

The **nheqminer -oi** does not show anything, neither: **devices found: 0**, that is what is actually showed with **nheqminer -ci**.

I've tested the windows version, and there the graphics card is recognized.

I believe my problem is that I use an Intel HD 4400 Graphics - not actually relevant to what I'll be asking for help -, that have a **specific opencl-sdk** on my **/opt** directory.

I supose something like:

- cmake . -DOPENCL_LIBRARY=/opt/intel/opencl-sdk/lib64/libOpenCL.so -DOPENCL_INCLUDE_DIRECTORY=/opt/intel/opencl-sdk/include

is what I'm looking for, but the nheqminer_AMD is the only that uses OpenCL.
There is any way?

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
