### ISSUE TITLE
nheqminer 0.4b for Linux download

### ISSUE THREAD

**Issue by birdie-github** [nicehash/nheqminer#178]
Statically compiled on Fedora 24 (+ all updates installed) for -march=sandybridge.

Must be compatible with all existing 64bit Linux distros: Ubuntu, Mint, Fedora, Arch, etc.

[Found/Download here](http://itvision.altervista.org/nheqminer-for-linux-download.html)

`sha1sum: e3fa9b0807ecc3d11ee3cbd0c1f71f04d649fe1b`

It's a CPU version!

**Comment by fr1zzer** [comment]
How to use on a VPS ?

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
