### ISSUE TITLE
32-bit windows

### ISSUE THREAD

**Issue by deshume6** [nicehash/nheqminer#184]
Hello. Will it be portable for 32-bit Windows 10? I can't run this one, there is an error of "versions". Translation of pic is: "Impossible to run this app on your PC. Contact to creator of app"
![2016_11_7_23_48_17](https://cloud.githubusercontent.com/assets/19998751/20075833/f8a9382e-a546-11e6-8f7d-68be0162996d.jpg)

**Comment by foxwarernd** [comment]
run only x64 OS

**Comment by deshume6** [comment]
Why?
Would you make it portable for x32, please?:)

**Comment by foxwarernd** [comment]
Features of the program for mining - is connected with memory addressing and working with CPU cycles

**Comment by chronosek** [comment]
i think it is possible to port it on 32-bit, but any functions with assembly (like whole xenoncat) was for x64 and you need drop it, tromp solver and cuda tromp maybe opencl could work, but it would be much work to change all

**Comment by deshume6** [comment]
I think if it is possible even with that minuses described by chronosek... try it, please:)

**Comment by S74nk0** [comment]
There aren't any plains to support 32bit builds.
Closing issue...
