### ISSUE TITLE
Update silentarmy to v4 in order to support NVIDIA GPUs

### ISSUE THREAD

**Issue by KexyBiscuit** [nicehash/nheqminer#185]
https://github.com/mbevand/silentarmy/commit/a03e30838f1cdc182d2041cabc25f209721d7bbc
https://github.com/mbevand/silentarmy/releases/tag/v4

**Comment by chronosek** [comment]
nah i did try that and opencl had the same performance as cuda, i wonder if amd opencl will slow after that update, if yes then there is no point of update

**Comment by KexyBiscuit** [comment]
@chronosek If possible we can let NVIDIA GPUs to run v4, other to run v3.
My NVIDIA GPU cannot run CUDA ver., and I haven't had time to open that issue.🌚

**Comment by chronosek** [comment]
how can nvidia can not run cuda .... nicehash should do better job compiling cuda_tromp.dll (they still not changed options on equi_miner.cu, and thats why it compile not for all cards)

**Comment by KexyBiscuit** [comment]
@chronosek I'll try the library, thank you.

**Comment by chronosek** [comment]
did it work?

**Comment by montvid** [comment]
I agree, silentarmy's v4 works with cuda better than tromp cuda. I am waiting for the update of nheqminer. Chronosek did you say there is a way to compile nheqminer with silentarmy v4? I did not understand your instructions.

**Comment by chronosek** [comment]
i do not know if you need compile whole nheqminer, cause i always recompile, but you can just try replace kernel.cl in your binary zcash/gpu directory with http://chronx.pl/opencl/kernel.cl (it is untouched kernel from silentarmy merged with param.h, it not cointain any nheqminer opts or changes)
I could not run with -ot option, so if you need more threads you need run whole instances
remeber to delete silentarmy gpu bin

**Comment by KexyBiscuit** [comment]
@chronosek Your library works on 760 Ti, having ~10 sols/s, 2x faster than OCL_XMP. Thank you a lot!
But I'm still looking forward to an updated silentarmy kernel... Well I have to say I can't compile it.

AFAIK, ETH is not suitable for Kepler because of the VRAM bandwidth is not enough.

**Comment by montvid** [comment]
Myself I can't compile nheqminer_AMD on ubuntu 16.04 with or without  silentarmy v4. 
`cd nheqminer/Linux_cmake/nheqminer_AMD && cmake . -DOPENCL_LIBRARY=/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so -DOPENCL_INCLUDE_DIRECTORY=/usr/local/cuda-8.0/targets/x86_64-linux/ && make -j $(nproc)`

**Comment by chronosek** [comment]
did you try just replace kernel.cl in working binaries 0.4b ? (or for linux you need compile?)

**Comment by montvid** [comment]
I need to compile

**Comment by chronosek** [comment]
what errors you have? problems with amd sdk? Maybe you can disable compiling amd part

**Comment by maztheman** [comment]
I forked the code and will be updating it if they don't.

**Comment by montvid** [comment]
Thanks for the good news. I guess you could ask for a merge but I don't know how. I fixed the nheqminer_tromp_cuda miner to mine gpu and cpu at once in another thread but don't know how to ask for a merge.

**Comment by maztheman** [comment]
I forked, and made a build that has silent army v4:

https://github.com/maztheman/nheqminer/releases/tag/0.4c

**Comment by montvid** [comment]
I would like to compile silentarmy for cuda gpu + xenoncat for cpu nheqminer. Would that be possible maztheman? How?

**Comment by maztheman** [comment]
right now silentarmy compiles for OpenCL.  There is no known cuda version of it, but I guess it wouldn't be impossible to do?  I think?  So for right now all I have is the OpenCL version (which works on any gpu) and xenoncat for cpu.

**Comment by montvid** [comment]
How to compile it without amd dependencies? This works for me but does not have a cpu miner:
[https://github.com/mbevand/silentarmy/blob/master/README.md#compilation-and-installation](url)
`cd nheqminer/Linux_cmake/nheqminer_AMD && cmake . -DOPENCL_LIBRARY=/usr/local/cuda-8.0/targets/x86_64-linux/lib -DOPENCL_INCLUDE_DIRECTORY=/usr/local/cuda-8.0/targets/x86_64-linux/include/ && make -j $(nproc)`

`[ 66%] Building CXX object CMakeFiles/nheqminer_AMD.dir/home/monika/miners/nheqminer/nheqminer/libstratum/StratumClient.cpp.o
In file included from /home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/ocl_device_utils.h:6:0,
                 from /home/monika/miners/nheqminer/nheqminer/main.cpp:11:
/home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:1404:20: error: ‘CL_DEVICE_TOPOLOGY_AMD’ was not declared in this scope
  F(cl_device_info, CL_DEVICE_TOPOLOGY_AMD, cl_device_topology_amd) \
                    ^
/home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:1423:36: note: in definition of macro ‘__CL_DECLARE_PARAM_TRAITS’
 struct param_traits<detail:: token,param_name>       \
                                    ^
/home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:1434:4: note: in expansion of macro ‘__PARAM_NAME_INFO_1_2’
    __PARAM_NAME_INFO_1_2(__CL_DECLARE_PARAM_TRAITS)
    ^
/home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:1423:46: error: template argument 2 is invalid
 struct param_traits<detail:: token,param_name>       \
                                              ^
/home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:1404:2: note: in expansion of macro ‘__CL_DECLARE_PARAM_TRAITS’
  F(cl_device_info, CL_DEVICE_TOPOLOGY_AMD, cl_device_topology_amd) \
  ^
/home/monika/miners/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:1434:4: note: in expansion of macro ‘__PARAM_NAME_INFO_1_2’
    __PARAM_NAME_INFO_1_2(__CL_DECLARE_PARAM_TRAITS)
    ^
CMakeFiles/nheqminer_AMD.dir/build.make:254: recipe for target 'CMakeFiles/nheqminer_AMD.dir/home/monika/miners/nheqminer/nheqminer/main.cpp.o' failed
make[2]: *** [CMakeFiles/nheqminer_AMD.dir/home/monika/miners/nheqminer/nheqminer/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_AMD.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_AMD.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by montvid** [comment]
maztheman I meant I want to compile your silentarmy miner for my nvidia gpu + cpu. How to do that? I get errors above.

**Comment by maztheman** [comment]
hmmmm....
as a hack you can add 
<
/*********************************
* cl_amd_device_memory_flags *
*********************************/
#define cl_amd_device_memory_flags 1
#define CL_MEM_USE_PERSISTENT_MEM_AMD       (1 << 6)        // Alloc from GPU's CPU visible heap

/* cl_device_info */
#define CL_DEVICE_MAX_ATOMIC_COUNTERS_EXT           0x4032

/*********************************
* cl_amd_device_attribute_query *
*********************************/
#define CL_DEVICE_PROFILING_TIMER_OFFSET_AMD        0x4036
#define CL_DEVICE_TOPOLOGY_AMD                      0x4037
#define CL_DEVICE_BOARD_NAME_AMD                    0x4038
#define CL_DEVICE_GLOBAL_FREE_MEMORY_AMD            0x4039
#define CL_DEVICE_SIMD_PER_COMPUTE_UNIT_AMD         0x4040
#define CL_DEVICE_SIMD_WIDTH_AMD                    0x4041
#define CL_DEVICE_SIMD_INSTRUCTION_WIDTH_AMD        0x4042
#define CL_DEVICE_WAVEFRONT_WIDTH_AMD               0x4043
#define CL_DEVICE_GLOBAL_MEM_CHANNELS_AMD           0x4044
#define CL_DEVICE_GLOBAL_MEM_CHANNEL_BANKS_AMD      0x4045
#define CL_DEVICE_GLOBAL_MEM_CHANNEL_BANK_WIDTH_AMD 0x4046
#define CL_DEVICE_LOCAL_MEM_SIZE_PER_COMPUTE_UNIT_AMD   0x4047
#define CL_DEVICE_LOCAL_MEM_BANKS_AMD               0x4048
#define CL_DEVICE_THREAD_TRACE_SUPPORTED_AMD        0x4049
#define CL_DEVICE_GFXIP_MAJOR_AMD                   0x404A
#define CL_DEVICE_GFXIP_MINOR_AMD                   0x404B
#define CL_DEVICE_AVAILABLE_ASYNC_QUEUES_AMD        0x404C

typedef union
{
    struct { cl_uint type; cl_uint data[5]; } raw;
    struct { cl_uint type; cl_char unused[17]; cl_char bus; cl_char device; cl_char function; } pcie;
} cl_device_topology_amd;

#define CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD            1
>

to the CL/CL_ext.h

**Comment by maztheman** [comment]
hmm or try using AMD's include folders...

**Comment by montvid** [comment]
silentarmy v4 miner compiles just fine with my current setup but not nheqminer. That's my problem :/

**Comment by maztheman** [comment]
sorry i only got windows building right now, youll have to use AMD's SDK to compile, probably

**Comment by montvid** [comment]
Thanks. I'm trying your build on w10 with intel hd graphics 5300. I get an error
clCreateBuffer (-61)
Hash tables will use 805.3 MB
Can you guess how to decrease silentarmy solver intensity from default 20 to 18 or 16 in nheqminer? I found out it solves the problem but I don't know where to change it in nheqminer windows build?

**Comment by maztheman** [comment]
there is in the param.h a #define NR_ROWS_LOG 20 you can change it to #define NR_ROWS_LOG 16
and then  nheqminer/3rdparty/silentarmy/16_kernel.cl can be moved to zcash/gpu/kernel.cl

**Comment by chronosek** [comment]
i hope you know that deleting platform will not work for all (cause usual intel is on platform 0)

**Comment by maztheman** [comment]
Not deleting just ignoreing it, Since it can be found out by the device.

**Comment by chronosek** [comment]
i mean it found device on platform 0 and that was intel (what was not working), didnt find any gpu from platform 1 and have there few cards

**Comment by maztheman** [comment]
BTW I got the CUDA SilentArmy V4 build working its released here:
https://github.com/maztheman/nheqminer/releases/tag/v0.4d

**Comment by montvid** [comment]
How do you compile it on ubuntu?
