### ISSUE TITLE
LOW PRIORITY: Add information to the -oi command

### ISSUE THREAD

**Issue by maztheman** [nicehash/nheqminer#188]
I believe the parameter "CL_DEVICE_MAX_MEM_ALLOC_SIZE" should be added to the information screen as this will indicate if the GPU will be "compatible" with this miner.  I believe this value should be greater than "HT_SIZE" or else the gpu will get errors on either 1) clCreateBuffer or 2) clEnqueueNDRangeKernel

**Comment by philipperemy** [comment]
@maztheman good idea actually.

Just out of curiosity,

`|    1      3882    C   ./nheqminer                             568MiB |`

Do you know how to increase this apparent value that the GPU allocates? Setting something like x MiB?

Thanks!

**Comment by maztheman** [comment]
The only way to change the amount of memory it allocates is by changing the
algorithm the program uses.  It is very technical, the issue I opened here
is to at least give you information on why the program was not working for
a user.
