### ISSUE TITLE
Windows GPU Mining Broken When Launching from Another EXE

### ISSUE THREAD

**Issue by basicsk8r13** [nicehash/nheqminer#189]
When launching the GPU mining on Intel GPU from command line it works fine.

However when launching it using CreateProcess in C++ it breaks for some reason.  
Says ioerror.

Any idea why this is? I've tried CreateProcess, System("cmd line command to launch it with parameters") and a few others.  Launching it from another exe with CPU mining only works fine it's just GPU that breaks it.  Using the same parameters and launching GPU mining from command prompt window works. too.   Just can't launch from another exe.

**Comment by basicsk8r13** [comment]
When launching from command prompt all miner threads start up first for CPU, then the GPU thread.  Then it connects to stratum and displays clCreateBuffer (-61) twice before beginning to run fine. 


When launching from within another application it starts up the CPU threads, then connects to stratum, then launches the GPU thread which has an iostream stream error.  I'm wondering why does it not launch the GPU thread fast enough when the miner is launched from within another application even if I use 

system("start C:\\Users\\user\\AppData\\Roaming\\ZMine\\Zmine.exe -l us1-zcash.flypool.org:3333 -u t1N1hcb6SKApY5aWT3cC924EHoKE712xp5X.worker1 -ov 0 -op 0 -od 0");
	

For example?

**Comment by Kayfolom** [comment]
Try to specify the working folder (C:\Users\user\appdata\roaming\zmine\) in CreateProcess
_In_opt_ LPCTSTR  lpCurrentDirectory,

try running with cmd.exe /C
"cmd.exe /C C:\\Users\\user\\appdata\\roaming\\zmine\\zmine.exe"

**Comment by maztheman** [comment]
CD %~dp0
Nheqminer.exe ...

It's looking for a file in a relative path, so you need to change dir. Running from another exe you need to set the start in path.
