### ISSUE TITLE
AMD GPU Mining Not Working

### ISSUE THREAD

**Issue by dtawom** [nicehash/nheqminer#191]
I'm getting 0 Sols/sec with AMD GPU mining for on a R7 260x on Win 10 x64. I'm running with just the GPU switch and it is detecting the card properly at the beginning. Mining with the cpu switch works fine, and the gpu switch works fine on my other Nvidia system. 
The switches I'm using are: nheqminer.exe -l stratum.zcash.nicehash.com:3357 -u mypublicaddress -t 0 -od 0 
Note: Per a suggestion on another thread I have tried both the 15.12 drivers and the 15.11 drivers with the same results.  I don't think the drivers are the only problem. Anything other suggestions for me to try would be much appreciated, like OS version, or other applications that might be interfering with it.
The below picture is the results I was getting with the 15.12 drivers, but I got the same results with the newest drivers from AMD as well as the 15.11 drivers.
![gpu](https://cloud.githubusercontent.com/assets/23352016/20135003/0da4c3f0-a61a-11e6-8044-6f30ea85fd2e.jpg)

**Comment by maztheman** [comment]
Looks like you don't have enough VRAM.  Long story short is some cards can't single allocate 800mb. This issue is solved with v4 silent army. I forked the code and updating to v4. I already have working builds so just be patient for the moment

**Comment by montvid** [comment]
Try Genoil's ZEC miner with -i 16 or 18. It should work:
-i parameter sets 2-log of equihash bucket size & OpenCL global work size. Only the following values are supported: 20, 19, 18, 16. Lower values will usually lower performance, but free up GPU resources for desktop work or dual mining.

**Comment by maztheman** [comment]
I forked, and made a build that has silent army v4:

https://github.com/maztheman/nheqminer/releases/tag/0.4c

**Comment by dtawom** [comment]
> https://github.com/maztheman/nheqminer/releases/tag/0.4c

Thanks maztheman, it's working great.  Hate to be a bother but I'm trying to start this up on another system that has an Nvidia GTX 580 w 1.5GB of VRAM and I'm having the same issue.  I've tried with both the 0.4c and the 0.4b with the same results.

**Comment by maztheman** [comment]
With the gtx 580 since it's only open CL 1.1. That could be a reason why it won't compile.  I'm working on a cuda version. Stay tuned.

**Comment by aaronsace** [comment]
@maztheman have you got a v5 fork?

**Comment by maztheman** [comment]
I'm working on it. It's almost ready just working out some some bugs.  I know a lot of people are waiting but I'm out of town and so it'll have to wait. Thanks for your patience.

**Comment by dtawom** [comment]
@maztheman the latest 0.4g release is crashing on workstations with Radeon cards.  The two that I've seen this behavior on have a r7 260 and an integrated r7 apu.  Saw somebody boasting about 100 sol/s on a R9 nano card with somebody else's release so I've got a couple fury's on the way.  Hopefully Silentarmy will do just as well.  I really like your build and appreciate your help.  I thought adding color coding to the lines was a nice touch in the last release.

**Comment by maztheman** [comment]
It's crashing probably because of old bin files. Please delete them and it'll probably work.   I'm updating to v5 pretty soon here. Sorry for the problem

**Comment by dtawom** [comment]
@maztheman I noticed you "#Added Gtx 500 series compatibility with v0.4g_sm20" so I tried it out today, but I'm still getting 0 sol/s with GTX 580 1.5GB
BTW clearing the bin files did stop the crashing so I'm making sure to clear the directory before extracting the newest releases.

Thanks in Advance,

**Comment by mojsze** [comment]
Hello.
So Radeon r7 260x working without problem now? What is hashrate on the newest software?

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
