### ISSUE TITLE
no silentarmy intensity setting

### ISSUE THREAD

**Issue by montvid** [nicehash/nheqminer#193]
My intel gpu hangs trying to mine with nheqminer silentarmy but with Genoil's ZEC miner it works when I set it to 16 or 18. 19, 20 hangs. I can't find the intensity setting on nheqminer gpu miner.

Genoil's ZEC miner
-i parameter sets 2-log of equihash bucket size & OpenCL global work size. Only the following values are supported: 20, 19, 18, 16. Lower values will usually lower performance, but free up GPU resources for desktop work or dual mining.

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
