### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by aaronsace** [nicehash/nheqminer#2]
Just get 0 H/s, 0 Sol/s. 

Don't know why there is two versions either: 
nheqminer_x64_AVX.exe
nheqminer_x64_SSE2.exe

Edit: Just seems to be an issue with 'eu'; 'usa' works fine. Odd...

**Comment by nicehashdev** [comment]
Most of the pools are very unstable at this point and most of orders pointing to the same pool. When pool goes down, most of orders are dead and all miners disconnected (plus new miners cannot connect). This will surely resolve before launch on 28th.
