### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'cuda_tromp_75.lib'

### ISSUE THREAD

**Issue by basicsk8r13** [nicehash/nheqminer#207]
Nvm

**Comment by RMI78** [comment]
I have the same issue, tell me what's wrong and how to solve it please

**Comment by Moardread** [comment]
The solution is to go to: Properties : ConfigurationProperties : Linker : Input : Additional Dependencies and remove the line that says: cuda_tromp_75.lib

If you get the same problem for any of the others then you can do the following:
cpu_tromp_SSE2.lib
C:\Users\XXXXXXXXXXXXX\Documents\nheqminer-master\nheqminer\x64\Debug\cpu_tromp_SSE2.lib

of course changing the location to the location of the file on your pc.

You will them need to copy the cpu_tromp_SSE2.lib file into the x64\Release directory.
