### ISSUE TITLE
No serwer ?

### ISSUE THREAD

**Issue by zjac** [nicehash/nheqminer#210]
It worked very, yet yesterday. Suddenly problems. Someone knows something?
![11](https://cloud.githubusercontent.com/assets/17382302/20643960/032138a8-b427-11e6-9148-fbae60b483c1.JPG)

**Comment by AWEAIR** [comment]
The Zcash nicehash Server are closed. You must Switch the pool.

**Comment by zjac** [comment]
@AWEAIR 
What Now For the best pool ? Thnx
