### ISSUE TITLE
cmake fails - CMakeList.txt Line 157 build

### ISSUE THREAD

**Issue by geraldfrank** [nicehash/nheqminer#211]
CMakeList.txt Line 157 build failure cannot find source file
157:add_executable(${PROJECT_NAME} ${SOURCE_FILES})

root@foo:~/src/nheqminer-0.4a# cd Linux_cmake/nheqminer_AMD && cmake . && make -j $(noproc)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   log_setup
--   log
--   date_time
--   filesystem
--   thread
-- Configuring done
CMake Error at CMakeLists.txt:157 (add_executable):
  Cannot find source file:

    ../../ocl_xpm/ocl_device_utils/cl_ext.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Build files have been written to: /root/src/nheqminer-0.4a/Linux_cmake/nheqminer_AMD
root@foo:~/src/nheqminer-0.4a/Linux_cmake/nheqminer_AMD#

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
