### ISSUE TITLE
build sucessfull but i got same error when run the program

### ISSUE THREAD

**Issue by rikad** [nicehash/nheqminer#212]
i used debian wheezy with intel xeon server

i got this error

`Setting log level to 2
nheqminer_cpu_xenoncat: malloc.c:3096: sYSMALLOc: Assertion (old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 * (sizeof(size_t))) - 1)) & ~((2 * (sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long)old_end & pagemask) == 0)' failed.
Aborted`

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
