### ISSUE TITLE
Error in OpenCL.dll

### ISSUE THREAD

**Issue by Slavenin** [nicehash/nheqminer#214]
Hi!
I run 
```bash
nheqminer.exe -t 8 -l europe.equihash-hub.miningpoolhub.com:20570 -u user.worker -p x
```
on windows 7 system from latest build. But this computer have videocard from IBM. I got an error
>the entry point in the procedure could not be found, clReleaseDevice
![26444a172382_001](https://cloud.githubusercontent.com/assets/4180077/20879901/e03a658c-bae6-11e6-9362-1b87659d6a74.png)

I copy opencl.dll in miner folder, but this not work.

**Comment by computeronix** [comment]
Copy OpenCL.dll from https://github.com/nicehash/NiceHashMiner/releases/download/1.7.3.11/NiceHashMiner_v1.7.3.11.zip and place it in the same directory as nheqminer.exe

The DLL needs to be included in the release zip

**Comment by computeronix** [comment]
https://github.com/computeronix/nheqminer/blob/master/OpenCL.dll?raw=true

**Comment by S74nk0** [comment]
OpenCL solver are dropped from **nheqminer**. Latest [release](https://github.com/nicehash/nheqminer/releases/tag/0.5b).
Closing issue...
