### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by joyivan** [nicehash/nheqminer#216]
after cmake .
when I run make ,it is not successful like this .

### `[ 11%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/amount.cpp.o
[ 23%] [ 23%] [ 29%] [ 35%] [ 41%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/api.cpp.o
[ 47%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/crypto/sha256.cpp.o
Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/arith_uint256.cpp.o
[ 52%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/json/json_spirit_value.cpp.o
Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/json/json_spirit_writer.cpp.o
[ 58%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/json/json_spirit_reader.cpp.o
[ 64%] [ 70%] [ 76%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/uint256.cpp.o
Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o
Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/primitives/block.cpp.o
Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/main.cpp.o
Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/speed.cpp.o
[ 82%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/utilstrencodings.cpp.o
[ 88%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/StratumClient.cpp.o
[ 94%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/cuda_tromp/cuda_tromp.cpp.o
[100%] Building CXX object CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/cpu_tromp/blake2/blake2bx.cpp.o
Linking CXX executable nheqminer_cuda_tromp
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘ZcashMiner<SolverStub, cuda_tromp, SolverStub>::doBenchmark(int, int, int, int*, int*, int*, int, int, int*)’中：
ZcashStratum.cpp:(.text._ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_]+0x1be)：对‘cuda_tromp::cuda_tromp(int, int)’未定义的引用
ZcashStratum.cpp:(.text._ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_]+0x24b)：对‘cuda_tromp::getdevinfo()’未定义的引用
ZcashStratum.cpp:(.text._ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_]+0x384)：对‘cuda_tromp::start(cuda_tromp&)’未定义的引用
ZcashStratum.cpp:(.text._ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E11doBenchmarkEiiiPiS3_S3_iiS3_]+0xe25)：对‘cuda_tromp::stop(cuda_tromp&)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘ZcashMiner<SolverStub1, cuda_tromp, SolverStub>::doBenchmark(int, int, int, int*, int*, int*, int, int, int*)’中：
ZcashStratum.cpp:(.text._ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_]+0x1be)：对‘cuda_tromp::cuda_tromp(int, int)’未定义的引用
ZcashStratum.cpp:(.text._ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_]+0x24b)：对‘cuda_tromp::getdevinfo()’未定义的引用
ZcashStratum.cpp:(.text._ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_]+0x384)：对‘cuda_tromp::start(cuda_tromp&)’未定义的引用
ZcashStratum.cpp:(.text._ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE11doBenchmarkEiiiPiS4_S4_iiS4_]+0xe25)：对‘cuda_tromp::stop(cuda_tromp&)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘bool benchmark_solve_equihash<cuda_tromp>(CBlock const&, char const*, unsigned int, cuda_tromp&)’中：
ZcashStratum.cpp:(.text._Z24benchmark_solve_equihashI10cuda_trompEbRK6CBlockPKcjRT_[_Z24benchmark_solve_equihashI10cuda_trompEbRK6CBlockPKcjRT_]+0x1f6)：对‘cuda_tromp::solve(char const*, unsigned int, char const*, unsigned int, std::function<bool ()>, std::function<void (std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned long, unsigned char const*)>, std::function<void ()>, cuda_tromp&)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘ZcashMiner<SolverStub1, cuda_tromp, SolverStub>::ZcashMiner(int, int, int*, int*, int*, int, int, int*)’中：
ZcashStratum.cpp:(.text._ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubEC2EiiPiS4_S4_iiS4_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubEC5EiiPiS4_S4_iiS4_]+0x180)：对‘cuda_tromp::cuda_tromp(int, int)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘ZcashMiner<SolverStub, cuda_tromp, SolverStub>::ZcashMiner(int, int, int*, int*, int*, int, int, int*)’中：
ZcashStratum.cpp:(.text._ZN10ZcashMinerI10SolverStub10cuda_trompS0_EC2EiiPiS3_S3_iiS3_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_EC5EiiPiS3_S3_iiS3_]+0x180)：对‘cuda_tromp::cuda_tromp(int, int)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘void ZcashMinerThread<SolverStub1, cuda_tromp, SolverStub, cuda_tromp>(ZcashMiner<SolverStub1, cuda_tromp, SolverStub>*, int, int, cuda_tromp&)’中：
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI11SolverStub110cuda_tromp10SolverStubS1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE5startEv]+0x99)：对‘cuda_tromp::getdevinfo()’未定义的引用
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI11SolverStub110cuda_tromp10SolverStubS1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE5startEv]+0x44b)：对‘cuda_tromp::start(cuda_tromp&)’未定义的引用
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI11SolverStub110cuda_tromp10SolverStubS1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE5startEv]+0xbb9)：对‘cuda_tromp::solve(char const*, unsigned int, char const*, unsigned int, std::function<bool ()>, std::function<void (std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned long, unsigned char const*)>, std::function<void ()>, cuda_tromp&)’未定义的引用
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI11SolverStub110cuda_tromp10SolverStubS1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI11SolverStub110cuda_tromp10SolverStubE5startEv]+0x126e)：对‘cuda_tromp::stop(cuda_tromp&)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o：在函数‘void ZcashMinerThread<SolverStub, cuda_tromp, SolverStub, cuda_tromp>(ZcashMiner<SolverStub, cuda_tromp, SolverStub>*, int, int, cuda_tromp&)’中：
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI10SolverStub10cuda_trompS0_S1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E5startEv]+0x99)：对‘cuda_tromp::getdevinfo()’未定义的引用
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI10SolverStub10cuda_trompS0_S1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E5startEv]+0x44b)：对‘cuda_tromp::start(cuda_tromp&)’未定义的引用
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI10SolverStub10cuda_trompS0_S1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E5startEv]+0xbb9)：对‘cuda_tromp::solve(char const*, unsigned int, char const*, unsigned int, std::function<bool ()>, std::function<void (std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned long, unsigned char const*)>, std::function<void ()>, cuda_tromp&)’未定义的引用
ZcashStratum.cpp:(.text._Z16ZcashMinerThreadI10SolverStub10cuda_trompS0_S1_EvP10ZcashMinerIT_T0_T1_EiiRT2_[_ZN10ZcashMinerI10SolverStub10cuda_trompS0_E5startEv]+0x126e)：对‘cuda_tromp::stop(cuda_tromp&)’未定义的引用
CMakeFiles/nheqminer_cuda_tromp.dir/home/joyian/downloads/nheqminer/nheqminer/main.cpp.o：在函数‘print_cuda_info()’中：
main.cpp:(.text+0x43b)：对‘cuda_tromp::getcount()’未定义的引用
main.cpp:(.text+0x522)：对‘cuda_tromp::getinfo(int, int, std::string&, int&, std::string&)’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [nheqminer_cuda_tromp] 错误 1
make[1]: *** [CMakeFiles/nheqminer_cuda_tromp.dir/all] 错误 2
make: *** [all] 错误 2
`

WHY?

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
