### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jRazer** [nicehash/nheqminer#217]
Try to build only windows cpu miner - Exit with error:
error C1083: CL/opencl.h: No such file or directory ocl_device_utils\cl_ext.hpp
177	1	ocl_device_utils
How fix it?

**Comment by S74nk0** [comment]
OpenCL solver are dropped from **nheqminer**. Latest [release](https://github.com/nicehash/nheqminer/releases/tag/0.5b) or build the latest sources.
Closing issue...
