### ISSUE TITLE
Windows 0.4a and 0.4b (CPU) miner receives new job, then quits.

### ISSUE THREAD

**Issue by Mitokia** [nicehash/nheqminer#221]
I was able to get the windows miner connected, but as soon as it gets a new job, it stops running. I tried making a .bat file to run with the parameters I need, and tried running directly from the command line. Can anyone give me a hand? I have the same issue trying to run version 0.4a and 0.4b.

![sin titulo](https://cloud.githubusercontent.com/assets/24844773/21569226/ba326c88-ce99-11e6-9f73-75855c5608f0.png)

**Comment by Mitokia** [comment]
the debug output looks like this. 

![sin titulo](https://cloud.githubusercontent.com/assets/24844773/21569289/5cefac10-ce9a-11e6-8961-c1aff5bc1825.png)

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
