### ISSUE TITLE
Apologies

### ISSUE THREAD

**Issue by TehMerkMods** [nicehash/nheqminer#239]
I Apologise for my remarks I was just angry

**Comment by Moocow9m** [comment]
Sir you need to calm down.

**Comment by TehMerkMods** [comment]
@Moocow9m would you be calm when you find out you have a virus which is using your GPU as an ASIC Miner? and when you find out and trace it back to the owner to find out the program is open source.... would you be calm

**Comment by pallas1** [comment]
The miner is opensource, not the virus :-)

**Comment by Moocow9m** [comment]
@TehMerkMods that's why I build my own version rather than just blindly downloading one.

**Comment by TehMerkMods** [comment]
@Moocow9m i downloaded a mod menu for FiveM with this inside

**Comment by Moocow9m** [comment]
@TehMerkMods then please look where the mod got it or replace the mod's version with one built from the repo as I have not had any problems.

**Comment by TehMerkMods** [comment]
@Moocow9m Well like i said I'm going to reverse the application in my spare time and get the twats bitcoin
