### ISSUE TITLE
Avast detecting Malware !! 

### ISSUE THREAD

**Issue by SolidFiber** [nicehash/nheqminer#251]
just downloaded the latest build, 5c but Avast Pro antivirus is detecting malware !! any explanation ?  because that didn't happen when I downloaded Bitcoin miners

**Comment by aaronsace** [comment]
It's open source and created by _the infamous_ NiceHash. It's a false positive like half the miners out there; as long as you use official sources then it's fine!

**Comment by philipperemy** [comment]
Disable your antivirus @SolidFiber

**Comment by SolidFiber** [comment]
So best solution I found is to add exclusion for NiceHash in Avast, so Avast will be running and stopping any other threat and also let's NiceHash miner to run normally

**Comment by luisdanielmesa** [comment]
It does have malware... Toojan.gen.2 and PUE.bitcoinminer... so, if you don't want to be part of a botnet I'd suggest you don't use anything from any of their repos... They even try to make you "update" your Antminers with their firmware, LOL

**Comment by philipperemy** [comment]
Have you looked at the code before posting? This is an open source project. The code is available. Search and try to find the malware code and post it here please. Gracias

**Comment by luisdanielmesa** [comment]
Don't cry... S74nk0 posted this... https://github.com/nicehash/NiceHashMiner/releases 

As I said... russian botnet and/or DDoS material, you can tell by the tackyness of the website and all... you could almost call it "kitsch".
Open Source Project? nope... not a single contributor is listed... it's private. If you download the binary, you'll get malware. I would ask you to enlighten me, but I work for IBM so,,, you'll have a hard time trying to lie to me about tech...

**Comment by philipperemy** [comment]
What you don't understand is that this code can actually be used inside a malware. It's a mining tool. So if you have another piece of code code, you can package the mining code to create a mining botnet. That's why Avast thinks it's a malware. Because for the standard user who does not mine, it would mean that it's a malware.

**Comment by luisdanielmesa** [comment]
I understand that PUA.bitcoinminer MIGHT be safe... no need to explain that to me, but...

I found a Trojan... 

Trojan.Gen.2

Exactly what part of mining requires the use of a trojan? LOL

**Comment by philipperemy** [comment]
It's false positive and flagged as a Trojan because this code was used in a bigger botnet project.

**Comment by luisdanielmesa** [comment]
Whatever you say little dude... happy coding 🤣 I would understand that, if I hadn't found the same Trojan 5 times in 5 different files. Why do you need to repeat the same code so much? Either the programmers are stupid and can't reuse code properly, or they're stupidly copy-pasting code around like monkeys. Either way, the recommendation is to NOT turn off the Antivirus software and notifications. Only a jackass would recommend turning those off.
