### ISSUE TITLE
Fails to build on ubuntu

### ISSUE THREAD

**Issue by hazinstore** [nicehash/nheqminer#28]
Getting a build failure on ubuntu

> `
> /usr/bin/ld: final link failed: Nonrepresentable section on output`

**Comment by hazinstore** [comment]
Finally got it to build using the cmake instructions, but it crashes immediately, I put it into gdb and this is the output...
>gdb nheqminer 
GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nheqminer...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/ubuntu/nheqminer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Equihash CPU Miner for NiceHash v0.1c
Thanks to Zcash developers for providing most of the code
Special thanks to tromp for providing optimized CPU equihash solver
Setting log level to 2
Program received signal SIGILL, Illegal instruction.
0x000055555568490b in boost::log::v2_mt_posix::aux::time_format_parser_callback<char>::on_extended_iso_time() ()

**Comment by S74nk0** [comment]
Please try [Linux](https://github.com/nicehash/nheqminer/tree/Linux) branch and reopen if it isn't fixed.
