### ISSUE TITLE
terminate called without an active exception Aborted (core dumped)

### ISSUE THREAD

**Issue by shayzluf** [nicehash/nheqminer#29]
I get [21:02:43][0x00007f653f36c700] stratum | Worker not authorized: 

Every time I run nheqminer

./nheqminer -l eu -u zcFr1cthUiHr2MDvtcyAVCj3FgCWMBGrcAaT4PUbLLaueyRurc94tRadFw8kV3NU3MYiDz6GyWBWaZ2zuVqWtHmodVafvYM -t 0 -od 0 1

**Comment by PaulioArmani** [comment]
I am having same issue.

**Comment by S74nk0** [comment]
Please try [Linux](https://github.com/nicehash/nheqminer/tree/Linux) branch and reopen if it isn't fixed.
