### ISSUE TITLE
posted sourcecode of 0.2 and 0.3 are not real

### ISSUE THREAD

**Issue by buzztiaan** [nicehash/nheqminer#30]
both 0.2 and 0.3 have been released with the source of 0.1 , please post it ...

**Comment by 9600-** [comment]
Second this. 
Would like to compile .3 on Linux.

**Comment by poiuty** [comment]
+

**Comment by iRybin** [comment]
yea sources are fake :(

**Comment by greenbigfrog** [comment]
to bring it on the point: nice try making also linux users etc. happy, but you FAILED!

**Comment by Zenitur** [comment]
Confirm. I have successfully compile Master GIT, but `strings nheqminer | grep zcash` show nothing. Also I've tried to search opencl, OpenCL, cuda, Cuda and CUDA.

**Comment by skive** [comment]
Confirm.

**Comment by S74nk0** [comment]
https://github.com/nicehash/nheqminer/tree/Windows here is a working Windows branch. Linux soon to come.
