### ISSUE TITLE
Application lock-ups (Windows 10)

### ISSUE THREAD

**Issue by cdokolas** [nicehash/nheqminer#315]
Running `nheqminer` v0.5c in the background (CPU mining) causes lock-ups on many other applications. Examples:
* Many applications lock-up for several seconds (up to half a minute) when saving files (this seems to happen immediately after saving the file)
* Web browsers and browser-based applications (e.g. Atom IDE) delay showing drop-down box contents for several seconds (drop-down box opens but content is not visible for a while)

I'm absolutely sure `nheqminer` is the culprit because I've repeatedly stopped it during such delays and responsiveness was restored immediately.

My specs:
* OS: Windows 10 Enterprise (64-bit)
* CPU: Intel i5-4590 (quad-core @ 3.3MHz)
* RAM: 16GB DDR3 running @ 1600MHz (avg in use: ~7.5GB)

**Comment by Amonomen** [comment]
What is the exact command line you're using to start the miner?  You really haven't provided any information to even guess what the issue could be.

**Comment by cdokolas** [comment]
This is how it runs (as a Windows service via NSSM): `nheqminer.exe -l eu.zec.slushpool.com:4444 -u someuser.name -t 6`

As to the guessing, I'm just stating the problem, throwing in some basic info, waiting to see if there are others experiencing the same. You can ask me anything you think might help you. IMHO, it has something to do with memory management.

**Comment by Amonomen** [comment]
I should have checked this before I posted.. A quick Google search shows that CPU only has 4 threads. Trying to run a CPU miner on n/n threads will cause a big performance loss let alone 1.5n/n threads. Try setting the thread count to 3 instead of 6.

**Comment by cdokolas** [comment]
Apologies not necessary. I made the change. Now CPU is @ ~87% total. I'll let you know how it goes.

Thanks a bunch.

**Comment by cdokolas** [comment]
It's been running for about 5 hours now and the only "problem" I have is that the hash rate has fallen by ~25%. This is to be expected though with 3 working cores instead of 4.
Thanks for the tip :)
