### ISSUE TITLE
Can't find boost_log

### ISSUE THREAD

**Issue by Zenitur** [nicehash/nheqminer#32]
http://pastebin.com/XH2gck6h

Can I disable the using of boost_log?

**Comment by S74nk0** [comment]
Hi @Zenitur. Please try building against a newer version of boost. **v1.52.0** was not tested. We have tested it with **v1.54.0+**

**Comment by Zenitur** [comment]
Is it neccessary? Is there an option to disable?

Ok, I have upgrade my Boost to 1.54. Also I've tried to rebuild Boost 1.52 with additional boost_log sources from there: https://sourceforge.net/projects/boost-log/files/boost-log2-snapshot-799.zip/download I have got libboost_log.1.52.so, but it's too old.
