### ISSUE TITLE
CUDA error 'invalid device ordinal' in func 'cuda_djezo:: getinfo' line 66

### ISSUE THREAD

**Issue by kovensky85** [nicehash/nheqminer#338]
Hi,
Got this error, any inputs?
![image](https://user-images.githubusercontent.com/34585209/34062265-ae2f5066-e1b9-11e7-81cd-08bace13936a.png)
thanks

**Comment by amitaymolko** [comment]
Hey @kovensky85 ,
How did you fix this issue?
