### ISSUE TITLE
How to GPU mine & receive ZCash on Ubuntu

### ISSUE THREAD

**Issue by JCBauza** [nicehash/nheqminer#35]
Seems GPU mine is not enabled when I build on Ubuntu nor being able to use a ZCash address. Anyone knows how to get those two things to work on Ubuntu? Thanks!

**Comment by Khaezzar** [comment]
i am in the same situation : no gpu mining and no zcash address

**Comment by DavBE** [comment]
Same here...

**Comment by buzztiaan** [comment]
because the source does not include gpu mining

**Comment by buzztiaan** [comment]
its the '0.1' miner source, not any other

**Comment by cornuwel** [comment]
So, are they only pushing binary windows-only for current versions?

**Comment by buzztiaan** [comment]
correct

**Comment by buzztiaan** [comment]
they only use github to appear legit, but its just a scheme, it seems, they dont reply to github issues either

**Comment by cornuwel** [comment]
Looks like it. They replied privately to my tweet: "Release date of the source is unknown ATM." Which sounds a lot like "never" to me.

**Comment by JCBauza** [comment]
They should release it as at the end of the day they make money of us mining on nicehash

**Comment by DavBE** [comment]
Go figure

**Comment by Zenitur** [comment]
Try Wine. https://github.com/Genoil/ZECMiner/issues/19

**Comment by cornuwel** [comment]
@JCBauza Actually, they don't. They make money off people who buy hashing power. As long as there are enough miners to satisfy demand, they make the same. 
Too much miners and even the lowest bids get satisfied, driving the price down.
It's happening right now, prices are plummeting : https://www.nicehash.com/?p=orders&a=24
Not saying I approve, but that's probably why they do it.

**Comment by S74nk0** [comment]
Sources are pushed. GPU on Linux is **work in progress**
