### ISSUE TITLE
"Ignoring non-clean job" and "0 Sols/s"

### ISSUE THREAD

**Issue by PixelPerfect** [nicehash/nheqminer#358]
My miner is connecting to the pool but will not actually mine, it isn't even driving my hardware at all while its running.

Running with ./nheqminer.exe -l zec.slushpool.com:4444 -u _USERNAME.WORKER_
(credentials obscured from this post)

**Comment by volker48** [comment]
I'm having the same issue. @PixelPerfect What CPU do you have? I have an AMD Ryzen 7 1800X and I'm wondering if that is part of the problem.

**Comment by CtrlC-Root** [comment]
Just to make sure you didn't make the same mistake as me, but it can take a while for the miner to accept the first job and report a non-zero speed. I ended up rebuilding it from source to make sure it wasn't a driver issue before I had the patience to let it run for 5 minutes and noticed it does in fact mine. 🤷‍♂️

**Comment by volker48** [comment]
@CtrlC-Root I don't think thats it because even the benchmark reports 0.

**Comment by PixelPerfect** [comment]
In my instance it was a silent failure caused by having a GPU too outdated to support the miner.
