### ISSUE TITLE
Hawaii GPU issue

### ISSUE THREAD

**Issue by Densets** [nicehash/nheqminer#36]
Not working for 290x and 295x2(basicly 2 290x) cards. All shares get rejected and sol/s shows in the thousands.

**Comment by ylpkm** [comment]
Working fine for me on 295x2. getting ~33 sols/s  just using opencl parameters from -h

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
