### ISSUE TITLE
How many Sols should you get as a minimum?

### ISSUE THREAD

**Issue by N3xigen** [nicehash/nheqminer#39]
I got an i7 - 3820 with hyperthreading mining on 7 cores and a R9 290 GPU.
Right now I'm mining with 27 sols in total and my GPU seems to be quite relaxed about it.
Is this a good amount of Sols for my gear or could I squeeze out way more juice than this?

![capture](https://cloud.githubusercontent.com/assets/23133307/19827846/34140080-9db6-11e6-8976-1b0236859596.PNG)

**Comment by N3xigen** [comment]
It went up to 32 sols by itself. I figure that this is about the limit of my GPU?

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
