### ISSUE TITLE
Multi-gpu mining

### ISSUE THREAD

**Issue by mehtaman** [nicehash/nheqminer#40]
Is there a readme for nheqminer_zcash.exe  and the different commands?
When I run:
nheqminer_zcash.exe -l eu -u WALLET -p x -t 6 -od 0 1 2 

Only one GPU is mining

**Comment by foxwarernd** [comment]
Get command line param with -h
Get cards numbers start with -oi  and input with -od number card

**Comment by Eyedol-X** [comment]
It builds bin files at the beginning and says "using GPU 1 as GPU 0" -- so it all looks like GPU 0, watch the log closely when starting the miner

**Comment by S74nk0** [comment]
Multi GPU works. Also CPU AMD and NVIDIA simultaneously work as well.
