### ISSUE TITLE
AMD issue with Intel Graphic

### ISSUE THREAD

**Issue by KL0nLutiy** [nicehash/nheqminer#43]
AMD not working with integrated Intel Graphic

**Comment by buzztiaan** [comment]
lol

**Comment by Eyedol-X** [comment]
Make sure you view the platform listing and set the -op parameter correctly

**Comment by ragnaroklow** [comment]
I think what he means to say is that if your IGPU is active for X reason, the miner crashes

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
