### ISSUE TITLE
nheqminer_zcash not present when building on Linux

### ISSUE THREAD

**Issue by urza** [nicehash/nheqminer#44]
The title says it. When following build-make instrucitons from readme page, on LInux (ubuntu 16.04) there is no nheqminer_zcash created.

**Comment by buzztiaan** [comment]
correct, the sources supplied dont match the 0.2 or 0.3 miner, its just the 0.1 miner sourcecode, which doesnt have the _zcash version

**Comment by DavBE** [comment]
👎

**Comment by JCBauza** [comment]
Is this getting updated?

**Comment by Elmit2015** [comment]
so, which source can we use?

**Comment by buzztiaan** [comment]
There isn't any, because nicehash are being dicks

**Comment by S74nk0** [comment]
Sources pushed. [Windows](https://github.com/nicehash/nheqminer/tree/Windows) and [Linux](https://github.com/nicehash/nheqminer/tree/Linux) branches. Windows should be stable Linux is work in progress.
