### ISSUE TITLE
 Rejected share

### ISSUE THREAD

**Issue by bellaj** [nicehash/nheqminer#45]
I m getting this error while running nheqminer 

`[2016-10-29 13:46:10.693807][0x000005bc]: stratum | Rejected share #1238 (Invalid Equihash solution)`

**Comment by Eyedol-X** [comment]
Happens here too across multiple miners, appears to be random. My guess is there is some pool/miner issue causing it.

**Comment by kntdookoo** [comment]
Try catalyst 16.3 if you are using an AMD. Only 1% rej now. 
http://support.amd.com/en-us/kb-articles/Pages/AMD_Radeon_Software_Crimson_Edition_16.3.aspx

**Comment by bellaj** [comment]
i am using Nvidia

**Comment by S74nk0** [comment]
Rejected shares are not a BUG. Not all share are always accepted.
