### ISSUE TITLE
650M NVIDIA CUDA doesn't work with 0.3b

### ISSUE THREAD

**Issue by zzlatev** [nicehash/nheqminer#47]
650M NVIDIA CUDA doesn't work with the 0.3 release.

**Comment by foxwarernd** [comment]
find ver 0.2a and test
In my situation with 750 ti only ver 0.2a

**Comment by Eyedol-X** [comment]
I had to get the latest 375.xx drivers from Nvidia to get my 780m to work, it did not previously work until I updated.

**Comment by blue-yu** [comment]
I have also problems with 750ti and old drivers. I will try to upgrade and run 0.3 release

**Comment by blue-yu** [comment]
375.70 driver, 6*750ti, Win7x64, also 0 Sol/s with 0.3a version. Please fix it...

**Comment by Eyedol-X** [comment]
Use -od and open CL as a workaround, I found it works on some of my older cards (680)

**Comment by foxwarernd** [comment]
for 750ti use 0.2a

**Comment by blue-yu** [comment]
Thanks. 0.3 workaround is working, but 0.2 is little faster...

**Comment by apkd** [comment]
0.3 fails on my 2x770gtx setup (on either or both cards (375.70 drivers)). I'm getting massive I/s (7k-8k) and 0 Sol/s. Works correctly on 0.2a.

**Comment by Rysio69** [comment]
For GT650M try using those DLL's: http://www.mediafire.com/file/bq78aa8ofo23x8n/CUDADll%27s.rar
For me, it seems to work. How ever I don't really see much performace increse :(

**Comment by chronosek** [comment]
0.3a version was compiled only for compute capability 5.2 , your card is older, you need compile cuda_tromp.dll for your card or use older (slower) from version 0.2a .... Or you can try dll compiled by me http://chronx.pl/cuda/cuda_tromp_0.3a.zip (cc2.x-cc6.2)

**Comment by S74nk0** [comment]
Issue related to older version.
Closing...
