### ISSUE TITLE
AMD GPU performance is awful

### ISSUE THREAD

**Issue by molitar** [nicehash/nheqminer#48]
RX 480 8GB 
R9 380x 4GB
R9 280x 3GB

GPU speed: 25 Sol/s

**Comment by kntdookoo** [comment]
Which catalyst drivers are you using?

**Comment by kntdookoo** [comment]
Try 16.3. Worked great on 390X. 
Link: http://support.amd.com/en-us/kb-articles/Pages/AMD_Radeon_Software_Crimson_Edition_16.3.aspx

**Comment by molitar** [comment]
I'm currently on 16.4 right now.

**Comment by kntdookoo** [comment]
Have you tried 15.1.2?

**Comment by molitar** [comment]
That does not work with RX 480 cards at all. I use to use that driver before I got my RX 480 for eth mining.

**Comment by jjziets** [comment]
Yes. I get 20% higher has using coinsfotall.io miner. I hope genoil get on part soon

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
