### ISSUE TITLE
Makefile:244: recipe for target 'nheqminer' failed

### ISSUE THREAD

**Issue by MrMighty** [nicehash/nheqminer#49]
Trying to Build on Google Cloud. I got this error. Any help?

_traits<char>, std::allocator<char> >&, std::locale const&)'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

Makefile:244: recipe for target 'nheqminer' failed
make: **\* [nheqminer] Error 1

**Comment by ColeMundus** [comment]
Im getting the same issues

**Comment by S74nk0** [comment]
Please try [Linux](https://github.com/nicehash/nheqminer/tree/Linux) branch and reopen if it isn't fixed.
