### ISSUE TITLE
No CPU optimisations with cmake build

### ISSUE THREAD

**Issue by asluchevskiy** [nicehash/nheqminer#5]
Hi,

There is no any CPU compiler optimisations with cmake build system.
You forgought to add them.

Just added 
```
add_definitions(-O3)
```
To `nheqminer/CMakeLists.txt` file

Before it was 1 H/s on my i7, now is 5H/s

**Comment by S74nk0** [comment]
Hi @asluchevskiy. Thanks for the report, good catch! It is fixed now.
