### ISSUE TITLE
nheqminer: 1: nheqminer: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by xJoeyv** [nicehash/nheqminer#52]
nheqminer: 1: nheqminer: Syntax error: "(" unexpected

^^ That is what shows up when I type "nheqminer -l eu -u {ADDRESS} -t {THREADS}" And obivous {} are replaced with values.

I run this on Ubunutu 14.04 Build with Cmake

**Comment by S74nk0** [comment]
Try with the latest [Linux](https://github.com/nicehash/nheqminer/tree/Linux) sources. -l location is now changed to set host and port.

**Comment by xJoeyv** [comment]
root@{***}:~/nheqminer/Linux_cmake/nheqminer_cpu# sh nheqminer_cpu -l eu -u ADDRESS.Server -t 4
nheqminer_cpu: 1: nheqminer_cpu:ELF: not found
nheqminer_cpu: 2: nheqminer_cpu: Syntax error: ")" unexpected
