### ISSUE TITLE
Didn't work in Wine 64-bit

### ISSUE THREAD

**Issue by Zenitur** [nicehash/nheqminer#53]
During nheqminer source code will not updated (https://github.com/nicehash/nheqminer/issues/30), I've tried to start latest Windows build in Linux using Wine 64-bit.

There is a crash log: http://pastebin.com/y77Y2nY4

Wine is really can start ZCash miners, for example ZECMiner: https://github.com/Genoil/ZECMiner/issues/19

**Comment by S74nk0** [comment]
Hi @Zenitur. Sources are now available. Linux branch is being updated (WIP).
