### ISSUE TITLE
API protocol

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/nheqminer#55]
I run miner with a parameter -a 4444
Send to tcp 127.0.0.1:4444 {"method":"status"}#10#13
but I do not get a response. What am I doing wrong?

**Comment by aaronsace** [comment]
Go to localhost:4444 in the web browser.

**Comment by Kayfolom** [comment]
> Go to localhost:4444 in the web browser.
Nothing happens, and it should not. Judging from the source code API operates through TCP instead HTTP.
