### ISSUE TITLE
Fail OCL

### ISSUE THREAD

**Issue by juncraul** [nicehash/nheqminer#58]
Hello,
I'm getting endless "fail OCL" error in the console window when trying to mine with nheqminer_zcash.exe
Do you know what causes this issue?
I have msi rx 470 gaming x 4gb

The batch file i use is: nheqminer_zcash -l eu -u z-cash-address -t 0 -od 0 1

**Comment by aaronsace** [comment]
Please post the text before it spasm "fail OCL".

**Comment by juncraul** [comment]
![image](https://cloud.githubusercontent.com/assets/6085586/19837358/5d5da3f6-9eb0-11e6-9703-51b663dddfd1.png)

Thanks for the reply, here is a screenshot with what i have before the error.

**Comment by aaronsace** [comment]
Just get rid of the '1' at the end of the command. You don't have two GPUs.

**Comment by juncraul** [comment]
Thank you very much, it worked. Sorry for my mistake.

**Comment by DavBE** [comment]
What about closing this issue if it is resolved ?

**Comment by aaronsace** [comment]
Press close.
