### ISSUE TITLE
AMD rig - 4 GPUs

### ISSUE THREAD

**Issue by plast555** [nicehash/nheqminer#59]
Hello,
I have 3 rigs, 2 with 4 AMD GPUs and 1 with 3 GTX 1060 so, I noticed that when I start a miner, just 2 GPUs hashing and 2 GPUs rejecting hash.
I tried to start one by one and the same happened, so at the end I'm hashing with just 2 GPUs right now, so anyone knows how to manage conf .bat file to all 4 are working ?
Thx !

my conf .bat file is:
nheqminer.exe -l usa -u 1JXkjVWhyPjuxzvnrmf8Z8CF6ZyzGdmRtD.AMD1 -t 0 -op 0 -od 0 1
pause

with
nheqminer.exe -l usa -u 1JXkjVWhyPjuxzvnrmf8Z8CF6ZyzGdmRtD.AMD1 -t 0 -op 0 -od 0 1 2 3
pause
and with
nheqminer.exe -l usa -u 1JXkjVWhyPjuxzvnrmf8Z8CF6ZyzGdmRtD.AMD1 -t 0 -op 0 -od 2 3
pause

I'm getting 50% of rejects !!

**Comment by plast555** [comment]
btw, GTX 1060 works perfect, I'm getting with one GTX 1060 25 Sol, but with R9 280 getting just 8 Sol and with R9 290 12 Sol

**Comment by aaronsace** [comment]
Try switching to EU.

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
