### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by sammy007** [nicehash/nheqminer#6]
Following guide from readme.

```
make

../nheqminer/3rdparty/boost/predef/hardware/simd/x86.h:13:53: fatal error: boost/predef/hardware/simd/x86/versions.h: No such file or directory
```

of course boost is installed but ignored.

**Comment by S74nk0** [comment]
are you using the CMake build instructions?

**Comment by sammy007** [comment]
i7 CPU.

```
git clone https://github.com/nicehash/nheqminer.git
cd nheqminer
mkdir build
cd build
qmake ../nheqminer/nheqminer.pro
make
```

**Comment by S74nk0** [comment]
We will be deprecating this build system in the future. since it has shown to be problematic Use [these](https://github.com/nicehash/nheqminer#linux-cmake-recommended-tested-on-ubuntu-desktop-1404-and-1604-and-ubuntu-server-1404) instead. Reopen this issue if CMake build instructions do not work.
