### ISSUE TITLE
Unable to compile with AVX support

### ISSUE THREAD

**Issue by juanjgit** [nicehash/nheqminer#62]
$ cmake -DXENON=1 ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   log_setup
--   log
--   date_time
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
-- CXXFLAGS:  -std=c++11 -march=native
-- LIBS: /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_log_setup.so;/usr/lib/x86_64-linux-gnu/libboost_log.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- XENON: 1
-- XENONCAT: /home/juanje/nheqminer/nheqminer/external/equihash-xenon/Linux/asm/equihash_avx1.o
-- Configuring done
-- Generating done
-- Build files have been written to: /home/juanje/nheqminer/nheqminer/build
juanje@india:~/nheqminer/nheqminer/build$ make
Scanning dependencies of target nheqminer
[  5%] Building CXX object CMakeFiles/nheqminer.dir/main.cpp.o
[ 11%] Building CXX object CMakeFiles/nheqminer.dir/amount.cpp.o
[ 17%] Building CXX object CMakeFiles/nheqminer.dir/api.cpp.o
[ 23%] Building CXX object CMakeFiles/nheqminer.dir/arith_uint256.cpp.o
[ 29%] Building CXX object CMakeFiles/nheqminer.dir/crypto/ripemd160.cpp.o
[ 35%] Building CXX object CMakeFiles/nheqminer.dir/crypto/sha256.cpp.o
[ 41%] Building CXX object CMakeFiles/nheqminer.dir/json/json_spirit_reader.cpp.o
[ 47%] Building CXX object CMakeFiles/nheqminer.dir/json/json_spirit_value.cpp.o
[ 52%] Building CXX object CMakeFiles/nheqminer.dir/json/json_spirit_writer.cpp.o
[ 58%] Building CXX object CMakeFiles/nheqminer.dir/libstratum/StratumClient.cpp.o
[ 64%] Building CXX object CMakeFiles/nheqminer.dir/libstratum/ZcashStratum.cpp.o
[ 70%] Building CXX object CMakeFiles/nheqminer.dir/primitives/block.cpp.o
[ 76%] Building CXX object CMakeFiles/nheqminer.dir/speed.cpp.o
[ 82%] Building CXX object CMakeFiles/nheqminer.dir/trompequihash/blake2/blake2bx.cpp.o
[ 88%] Building CXX object CMakeFiles/nheqminer.dir/uint256.cpp.o
[ 94%] Building CXX object CMakeFiles/nheqminer.dir/utilstrencodings.cpp.o
make[2]: **\* No rule to make target '../external/equihash-xenon/Linux/asm/equihash_avx1.o', needed by 'nheqminer'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer.dir/all' failed
make[1]: **\* [CMakeFiles/nheqminer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by S74nk0** [comment]
@juanjgit yes this is broken but will be fixed in Linux branch soon.

**Comment by ngreatorex** [comment]
I've added a pull request #64 that fixes this in Linux branch

**Comment by juanjgit** [comment]
I see that it should be solved now. Thank you. Can you add build instructions for Linux to the "readme"?

**Comment by S74nk0** [comment]
Pull request accepted. Will update Readme now.

**Comment by S74nk0** [comment]
Build [instructions](https://github.com/nicehash/nheqminer/tree/Linux#linux-ubuntu-1404--1604-build--cpu_xenoncat) updated. Closing issue

**Comment by evanvz** [comment]
Been following thank you. Been using tpruvot build but not available anymore. Still working though. Small spelling mistake in Linux building instructions. Should be "sudo apt-get install cmake build-essential libboost-all-dev". Sorry (build-esenital)

**Comment by evanvz** [comment]
Linux instructions build on Ubuntu 16.04 Server. With tpruvot build I could ./nheqminer -l eu -u walletnumber.worker1, but it's not working anymore. What should I use if mining on nicehash pool! Thank you.

**Comment by evanvz** [comment]
Sorry, not sure if I'm doing it right: 
[15:28:24][0x00007f7f071af700] stratum | resolve: Service not found
[15:28:24][0x00007f7f071af700] stratum | Reconnecting in 3 seconds...
[15:28:27][0x00007f7f071af700] stratum | Connecting to stratum server eu:eu

**Comment by ngreatorex** [comment]
@evanvz you now need to specify the correct stratum host as it works with any pool.
e.g. "./nheqminer -l equihash.usa.nicehash.com:3357"

**Comment by evanvz** [comment]
@ngreatorex Thank you for the assist. Only found nheqminer_cpu under /nheqminer/Linux_cmake/nheqminer_cpu, no nheqminer.
Ran ./nheqminer_cpu -l equihash.usa.nicehash.com:3357 -u walletnumber.worker1 -p x and got this.
[16:07:21][0x00007f645639d700] stratum | Connecting to stratum server equihash.usa.nicehash.com:3357:3357
[16:07:22][0x00007f645639d700] stratum | resolve: Host not found (authoritative)
[16:07:22][0x00007f645639d700] stratum | Reconnecting in 3 seconds...

**Comment by ngreatorex** [comment]
@evanvz I think there was a bug that was fixed separately... try updating and re-compiling

**Comment by evanvz** [comment]
@ngreatorex Followed some other posts and it was fixed. Thanks for your help.... happy mining... just started a week or two ago. Set up with some old HP & IBM, so ya. NOt sure if this is the wright place to chat about types of mining, cloud mining and what rig to go for. Cheers.
