### ISSUE TITLE
Unable to compile 'Windows' branch

### ISSUE THREAD

**Issue by skive** [nicehash/nheqminer#63]
Using Visual Studio 2013.

Error   1   error MSB3073: The command "asm\fasm.exe asm\xenoncat_AVX.asm asm\xenoncatavx1.obj
asm\fasm.exe asm\xenoncat_AVX2.asm asm\xenoncatavx2.obj
:VCEnd" exited with code 9009.  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets  127 5   cpu_xenoncat

Error   2   error LNK1104: cannot open file 'pthreads\pthreadVC2.lib'   D:\Apps\Crypto\nheqminer-Windows\cpu_tromp\LINK cpu_tromp

Error   3   error C1083: Cannot open include file: 'CL/cl.h': No such file or directory d:\apps\crypto\nheqminer-windows\ocl_xpm\opencl.h   12  1   ocl_xpm

Error   4   error C1083: Cannot open include file: 'CL/cl.h': No such file or directory d:\apps\crypto\nheqminer-windows\ocl_xpm\opencl.h   12  1   ocl_xpm

Error   5   error C1083: Cannot open include file: 'CL/cl_ext.h': No such file or directory d:\apps\crypto\nheqminer-windows\ocl_xpm\ocl_device_utils\cl_ext.hpp    168 1   ocl_xpm

Error   6   error LNK1104: cannot open file 'cuda_tromp.lib'    D:\Apps\Crypto\nheqminer-Windows\nheqminer\LINK nheqminer

**Comment by buzztiaan** [comment]
if you can find where fasm.exe gets called , add -m524288 to the command line

from; http://board.flatassembler.net/topic.php?t=12800

**Comment by S74nk0** [comment]
Hi @skive. I'll push the fix now. .gitignore blacklisted the FASM bin

**Comment by S74nk0** [comment]
Pull the latest commit it should work now. Reopen if it does not work.

**Comment by skive** [comment]
Fasm error fixed with last commit. Other erroros still firing.

Error	103	error C1083: Cannot open include file: 'CL/cl_ext.h': No such file or directory	d:\apps\crypto\nheqminer-windows\ocl_xpm\ocl_device_utils\cl_ext.hpp	168	1	ocl_xpm
Error	104	error C1083: Cannot open include file: 'CL/cl.h': No such file or directory	d:\apps\crypto\nheqminer-windows\ocl_xpm\opencl.h	12	1	ocl_xpm
Error	105	error C1083: Cannot open include file: 'CL/cl.h': No such file or directory	d:\apps\crypto\nheqminer-windows\ocl_xpm\opencl.h	12	1	ocl_xpm
Error	106	error LNK1181: cannot open input file 'pthreads\pthreadVC2.lib'	D:\Apps\Crypto\nheqminer-Windows\cpu_tromp\LINK	cpu_tromp
Error	107	error LNK1181: cannot open input file 'cuda_tromp.lib'	D:\Apps\Crypto\nheqminer-Windows\nheqminer\LINK	nheqminer

**Comment by S74nk0** [comment]
I will have to update the README file. What is/are your target platform devices (CPU/NVIDIA/GPU)?

**Comment by skive** [comment]
Thanks. Target is CPU/AMD.

**Comment by S74nk0** [comment]
@skive OK. I have updated the master branch again to fix 3rdParty libs. If you don't want to compile against CUDA you can go to nheqminer C/C++ > Preprocessor properties and remove **USE_CUDA_TROMP**. If there are any more issues let us know on this thread. If you get things building then close it. Good luck.

**Comment by twatsnn** [comment]
there is no **USE_CUDA_TROMP** at stated area

**Comment by S74nk0** [comment]
Hm... can you please double check. Make sure you have solution configuration set to Release when you build that then build with ReleaseSSE2.

**Comment by twatsnn** [comment]
i was changed my os to ubuntu,now revert back after your message and now im downloading visual studio 2013 community.i will let you know when i test.sorry again.

**Comment by S74nk0** [comment]
No problem... no need to apologize.

**Comment by skive** [comment]
Platform: Windows 10 x64, Visual Studio Community 2013
Target architecture: avx2 cpu's, nvidia, amd

**Configuration: Debug**
Build runs successfully, but nheqminer show's 0 sol/s always

**Configuration: Release**
```
Error	56	error LNK1181: cannot open input file 'cpu_tromp_SSE2.lib'	D:\Apps\Crypto\nheqminer-Windows\nheqminer\nheqminer\LINK	nheqminer
```

**Configuration: ReleaseSSE2** 
```
Error	56	error LNK1181: cannot open input file 'cpu_tromp_AVX.lib'	D:\Apps\Crypto\nheqminer-Windows\nheqminer\nheqminer\LINK	nheqminer
```

**Comment by skive** [comment]
Last commits fixed this. Thank you for help.
