### ISSUE TITLE
Miner doesn't work with cuda mobile gpu's

### ISSUE THREAD

**Issue by twatsnn** [nicehash/nheqminer#69]
i have geforce 710m and its not working with only cuda option

launching parameters:
**nheqminer -cd 0 -t 0 -b
pause**

**Comment by chronosek** [comment]
if you have 0.3a version - it was compiled only for compute capability 5.2 , your card is older, you need compile cuda_tromp.dll for your card or use older (slower) from version 0.2a .... Or you can try dll compiled by me http://chronx.pl/cuda/cuda_tromp_0.3a.zip (cc3.0-cc6.2)

**Comment by bigrck64** [comment]
Thanks Chronosek, your DLL also works with GTX680 and driver 375.70 :+1:
