### ISSUE TITLE
Gentoo Support

### ISSUE THREAD

**Issue by bpvarsity** [nicehash/nheqminer#73]
Anyone been able to get this to work on gentoo? Struggling to get it working on one of my test servers.

**Comment by buzztiaan** [comment]
This issue is lacking any issue , 'struggling' isnt a error message

**Comment by bpvarsity** [comment]
Sorry I forgot to paste the output

 cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make
assemble.sh: line 1: ./fasm: Permission denied
assemble.sh: line 2: ./fasm: Permission denied

**Comment by S74nk0** [comment]
It must be a problem with the fasm binary. Please double check.

**Comment by bpvarsity** [comment]
I just installed  fasm 1.71.51 and same issue. hmm

**Comment by S74nk0** [comment]
I meant by the **Permission denied**. Can you execute the script manually? **sh assemble.sh** this will generate object files needed to link with the miner. The bundled **fasm** must have permissions to execute as a program. **ls -l fasm** in **cpu_xenoncat/Linux/asm/** directory this will show you if it has execution permissions.

**Comment by bpvarsity** [comment]
Same error if I execute the script manually. The fasm file was -rwxr-xr-x  and I tried -rwxrwxrwx as well and same issue.

**Comment by buzztiaan** [comment]
i just did chmod +x fasm in the asm dir, and it worked

**Comment by bpvarsity** [comment]
tx3 asm # chmod +x fasm
tx3 asm # sh assemble.sh
assemble.sh: line 1: ./fasm: Permission denied
assemble.sh: line 2: ./fasm: Permission denied

**Comment by buzztiaan** [comment]
is this a x86 machine? :)

**Comment by bpvarsity** [comment]
x64

**Comment by buzztiaan** [comment]
itanium? i dont think that will work

**Comment by bpvarsity** [comment]
Nope just a Xeon E3 cpu

**Comment by buzztiaan** [comment]
weird, same here, works

**Comment by bpvarsity** [comment]
hmm idk then. Tried it on two different Gentoo servers and same issue. Ill keep investigating

**Comment by bpvarsity** [comment]
I was able to get it to work. I changed the assemble file to use the fasm file located at /opt/fasm/fasm and now the script is working.

**Comment by bpvarsity** [comment]
Well it made it past fasm but now have the error below

[ 94%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/arpaetznick/nheqminer/cpu_xenoncat/xenoncat.cpp.o
[100%] Linking CXX executable nheqminer_cpu
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/nheqminer_cpu.dir/home/arpaetznick/nheqminer/nheqminer/main.cpp.o: undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/nheqminer_cpu.dir/build.make:521: recipe for target 'nheqminer_cpu' failed
make[2]: *** [nheqminer_cpu] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by S74nk0** [comment]
Look at [this](https://github.com/nicehash/nheqminer/pull/34/commits/c4a8320b79671f87d5ba9342b4be4eee49142845). pthreads library is not linking

**Comment by S74nk0** [comment]
Please comment if it works

**Comment by bpvarsity** [comment]
cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make
flat assembler  version 1.71.51  (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17322 bytes.
flat assembler  version 1.71.51  (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17361 bytes.
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   log_setup
--   log
--   date_time
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
-- Configuring done
CMake Error at CMakeLists.txt:125 (add_executable):
  Cannot find source file:

    main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: nheqminer
CMake Error: Cannot determine link language for target "nheqminer".
-- Generating done
-- Build files have been written to: /home/bpvarsity/nheqminer/Linux_cmake/nheqminer_cpu

**Comment by bpvarsity** [comment]
Did you mean for me to do this on this gentoo issue or on the debian issue I opened?

**Comment by buzztiaan** [comment]
> Cannot find source file:

hehe

did you put the CMakeLists.txt in nheqminer/nheqminer , mkdir build , cd build , cmake .. ?

Or are you trying to use the cmake file outside of sourcetree?

**Comment by bpvarsity** [comment]
I put the CMakeLists.txt in  nheqminer/nheqminer , did mkdir build , cd build , cmake .. and I get -- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   log_setup
--   log
--   date_time
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
-- Configuring done
CMake Error at CMakeLists.txt:125 (add_executable):
  Cannot find source file:

    trompequihash/blake2/blake2bx.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: nheqminer
CMake Error: Cannot determine link language for target "nheqminer".
-- Generating done
-- Build files have been written to: /home/bpvarsity/nheqminer/nheqminer

**Comment by buzztiaan** [comment]
well, thats at least a different error ;)

**Comment by bpvarsity** [comment]
haha yep trade one for another :P

**Comment by buzztiaan** [comment]
hmm weird, why are you building trompequihash?

**Comment by buzztiaan** [comment]
what i do ; 

copy Linux_cmake/nheqminer_cpu_xenoncat/CMakeLists.txt to right folder
mkdir build
cmake ..

done ....

**Comment by buzztiaan** [comment]
oh now i see, you were trying to get nheqminer_cpu to work .. dont think that will for now

**Comment by bpvarsity** [comment]
oh okay. Guess Ill wait for cpu to be supported.

**Comment by buzztiaan** [comment]
it already is

**Comment by buzztiaan** [comment]
there are 3 different 'cpu' cmake files, you just picked a nonworking one ;)

**Comment by bpvarsity** [comment]
lol okay. Which one should I use?

**Comment by buzztiaan** [comment]
https://github.com/nicehash/nheqminer/issues/73#issuecomment-257374175

**Comment by bpvarsity** [comment]
tx3 build # cmake ..
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   log_setup
--   log
--   date_time
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bpvarsity/nheqminer/cpu_xenoncat/build

Yay

**Comment by bpvarsity** [comment]
Making now :)

**Comment by bpvarsity** [comment]
Got another error now

[ 93%] Building CXX object CMakeFiles/nheqminer_cpu_xenoncat.dir/xenoncat.cpp.o
[100%] Linking CXX executable nheqminer_cpu_xenoncat
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/nheqminer_cpu_xenoncat.dir/home/bpvarsity/nheqminer/nheqminer/main.cpp.o: undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/nheqminer_cpu_xenoncat.dir/build.make:469: recipe for target 'nheqminer_cpu_xenoncat' failed
make[2]: *** [nheqminer_cpu_xenoncat] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu_xenoncat.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu_xenoncat.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by buzztiaan** [comment]
thats the same error as above, didnt you follow the advice from the link given to that?

**Comment by bpvarsity** [comment]
yes and it didnt work. Ill try again. Maybe I missed a line or something,

**Comment by buzztiaan** [comment]
remember to empty your entire build directory before 'cmake ..'-ing again

**Comment by bpvarsity** [comment]
cmake does not like the CMakeLists.txt that I was linked to for the pthreads fix . Only cmakes successfully with the one from the Linux_cmake folder. When I use the cmakelist in the link I getting the issue earlier

CMake Error at CMakeLists.txt:125 (add_executable):
  Cannot find source file:

    main.cpp

**Comment by buzztiaan** [comment]
'cannot find main.cpp' does not come familiar to you? :)

Well i give up

**Comment by bpvarsity** [comment]
okay fine. bye

**Comment by bpvarsity** [comment]
You can close this. Ill figure it out. Will start from scratch since something got messed up when doing some of the building. Thanks for your time.

**Comment by bpvarsity** [comment]
Started fresh on a new server and made some progress Guess I messed up somewhere awhile ago with the fasm issue. I made the two changes per the arch fix to the cmakelists.

This is the new error when making. 

[ 87%] Building CXX object CMakeFiles/nheqminer_cpu_xenoncat.dir/libstratum/StratumClient.cpp.o
[ 93%] Building CXX object CMakeFiles/nheqminer_cpu_xenoncat.dir/home/james/nheqminer/cpu_xenoncat/xenoncat.cpp.o
[100%] Linking CXX executable nheqminer_cpu_xenoncat
CMakeFiles/nheqminer_cpu_xenoncat.dir/home/james/nheqminer/cpu_xenoncat/xenoncat.cpp.o: In function `cpu_xenoncat::solve(char const*, unsigned int, char const*, unsigned int, std::function<bool ()>, std::function<void (std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned long, unsigned char const*)>, std::function<void ()>, cpu_xenoncat&)':
xenoncat.cpp:(.text+0x1c9): undefined reference to `EhPrepareAVX2'
xenoncat.cpp:(.text+0x1d5): undefined reference to `EhSolverAVX2'
xenoncat.cpp:(.text+0x2f1): undefined reference to `EhPrepareAVX1'
xenoncat.cpp:(.text+0x2fd): undefined reference to `EhSolverAVX1'
collect2: error: ld returned 1 exit status
CMakeFiles/nheqminer_cpu_xenoncat.dir/build.make:467: recipe for target 'nheqminer_cpu_xenoncat' failed
make[2]: *** [nheqminer_cpu_xenoncat] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu_xenoncat.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu_xenoncat.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by clintar** [comment]
https://github.com/nicehash/nheqminer/issues/9 that has a fix for the dso issue.

**Comment by jerrymag** [comment]
I am using #9 fix already but it did not fix the issue.

**Comment by clintar** [comment]
Ok, you said you started fresh. Are you not using the command in the README?
`cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make`

**Comment by bpvarsity** [comment]
Sorry I should have stated that better. I have run that command but I was told to use nheqminer_cpu_xenoncat so the command would be
cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu_xempmcat && cmake . && make

Correct?

I tried to run that with the default makelist that was in git as well as making one that matched the changed in #9 

**If I use the default list I get** 

[100%] Linking CXX executable nheqminer_cpu_xenoncat
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/nheqminer_cpu_xenoncat.dir/home/james/nheqminer/nheqminer/main.cpp.o: undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/nheqminer_cpu_xenoncat.dir/build.make:469: recipe for target 'nheqminer_cpu_xenoncat' failed
make[2]: *** [nheqminer_cpu_xenoncat] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu_xenoncat.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu_xenoncat.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**If I use the modified from #9 I get**

[  6%] Linking CXX executable nheqminer_cpu_xenoncat
CMakeFiles/nheqminer_cpu_xenoncat.dir/home/james/nheqminer/cpu_xenoncat/xenoncat.cpp.o: In function `cpu_xenoncat::solve(char const*, unsigned int, char const*, unsigned int, std::function<bool ()>, std::function<void (std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned long, unsigned char const*)>, std::function<void ()>, cpu_xenoncat&)':
xenoncat.cpp:(.text+0x1c9): undefined reference to `EhPrepareAVX2'
xenoncat.cpp:(.text+0x1d5): undefined reference to `EhSolverAVX2'
xenoncat.cpp:(.text+0x2f1): undefined reference to `EhPrepareAVX1'
xenoncat.cpp:(.text+0x2fd): undefined reference to `EhSolverAVX1'
collect2: error: ld returned 1 exit status
CMakeFiles/nheqminer_cpu_xenoncat.dir/build.make:467: recipe for target 'nheqminer_cpu_xenoncat' failed
make[2]: *** [nheqminer_cpu_xenoncat] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu_xenoncat.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu_xenoncat.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by clintar** [comment]
do you have fasm installed?

**Comment by bpvarsity** [comment]
Yes fasm 1.71.51

**Comment by bpvarsity** [comment]
Latest commits fixed the issue.
