### ISSUE TITLE
Linux branch’ binary is broken

### ISSUE THREAD

**Issue by loxal** [nicehash/nheqminer#74]
`./nheqminer_cpu -u t1JyivjnNwn35vsSYqeTQTyw1zH3DdHdM7q -t 6 -p x -l stratum.zcash.nicehash.com:3357`

gives me 

> [16:34:55][0x00007f69baffd700] miner#5 | Starting thread #5 (CPU-XENONCAT-AVX2) 
> [16:34:55][0x00007f69c20c1700] stratum | resolve: Host not found (authoritative)
> [16:34:55][0x00007f69c20c1700] stratum | Reconnecting in 3 seconds...
> [16:34:58][0x00007f69c20c1700] stratum | Connecting to stratum server stratum.zcash.nicehash.com:3357:3357
> [16:34:58][0x00007f69c20c1700] stratum | resolve: **Host not found (authoritative)**
> [16:34:58][0x00007f69c20c1700] stratum | Reconnecting in 3 seconds...
> [16:35:01][0x00007f69c20c1700] stratum | Connecting to stratum server stratum.zcash.nicehash.com:3357:3357

**Comment by buzztiaan** [comment]
this has already been fixed, pull the updates ;)

**Comment by loxal** [comment]
@buzztiaan just did, still get

> [16:41:26][0x00007fc7f4fa1700] stratum | Connecting to stratum server stratum.zcash.nicehash.com:3357:3357
> [16:41:26][0x00007fc7edffb700] miner#5 | Starting thread #5 (CPU-XENONCAT-AVX2) 
> [16:41:26][0x00007fc7f4fa1700] stratum | resolve: Host not found (authoritative)

**Comment by montyanderson** [comment]
This is my first time using the miner and I'm getting this too.

**Comment by loxal** [comment]
Ok, now it works, just pulled again :D Has been fixed a couple of mins ago 👍

**Comment by montyanderson** [comment]
okay, I've just pulled, I'll compile again. Thanks!

**Comment by evanvz** [comment]
Thank you. All good now after re-compile.
