### ISSUE TITLE
Boost Issue

### ISSUE THREAD

**Issue by bpvarsity** [nicehash/nheqminer#75]
cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make
flat assembler  version 1.71.57  (1280000 kilobytes memory)
3 passes, 0.4 seconds, 17322 bytes.
flat assembler  version 1.71.57  (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17361 bytes.
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1194 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.49.0

  Boost include path: /usr/include

  The following Boost libraries could not be found:

          boost_log_setup
          boost_log

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)

Boost_FOUND NOT FOUND
-- Configuring incomplete, errors occurred!

Does this script require a newer version of boost? If not then does anyone know how to fix this?

**Comment by S74nk0** [comment]
Hi @bpvarsity. That version was not tested but I think it just might be to old. **v1.54+** should work.

**Comment by bpvarsity** [comment]
Thanks Ill try 1.54 now

**Comment by S74nk0** [comment]
No problem. Will update README file.

**Comment by bpvarsity** [comment]
I compiled and install 1.54 but ran into another error.

cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make
flat assembler  version 1.71.57  (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17322 bytes.
flat assembler  version 1.71.57  (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17361 bytes.
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:732 (file):
  file Internal CMake error when trying to open file:
  /usr/include/boost/version.hpp for reading.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)


CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:745 (math):
  math cannot parse the expression: " / 100000": syntax error, unexpected
  exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)


CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:746 (math):
  math cannot parse the expression: " / 100 % 1000": syntax error, unexpected
  exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)


CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:747 (math):
  math cannot parse the expression: " % 100": syntax error, unexpected
  exp_MOD, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)


-- Boost version: ..
-- Found the following Boost libraries:
--   system
--   log_setup
--   log
--   date_time
--   filesystem
--   thread
-- Configuring incomplete, errors occurred!

**Comment by bpvarsity** [comment]
Ill make a new issue since its a different error
