### ISSUE TITLE
Host resolving issues

### ISSUE THREAD

**Issue by twoletters** [nicehash/nheqminer#76]
In main.cpp, you separate the location (-l param) into host and port (line 417), but in the two calls to function "start_mining" (lines 423 and 426) you use variable location instead of variable host. This is on the Linux branch.

**Comment by S74nk0** [comment]
This issue has been resolved on all branches. commit from [here](https://github.com/nicehash/nheqminer/commit/855493c2fb0423e1cb0108c3d713a25d6c807a71) on

**Comment by felixbrucker** [comment]
short question on this: will there be a windows release from these sources (soon)?
