### ISSUE TITLE
Debian 7 w/ boost 1.54 Issue

### ISSUE THREAD

**Issue by bpvarsity** [nicehash/nheqminer#77]
I compiled and install 1.54 but ran into the issue below. Any ideas would be appreciated 

cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make
flat assembler version 1.71.57 (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17322 bytes.
flat assembler version 1.71.57 (1280000 kilobytes memory)
3 passes, 0.5 seconds, 17361 bytes.
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:732 (file):
file Internal CMake error when trying to open file:
/usr/include/boost/version.hpp for reading.
Call Stack (most recent call first):
CMakeLists.txt:24 (find_package)

CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:745 (math):
math cannot parse the expression: " / 100000": syntax error, unexpected
exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
CMakeLists.txt:24 (find_package)

CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:746 (math):
math cannot parse the expression: " / 100 % 1000": syntax error, unexpected
exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
CMakeLists.txt:24 (find_package)

CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:747 (math):
math cannot parse the expression: " % 100": syntax error, unexpected
exp_MOD, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
CMakeLists.txt:24 (find_package)

-- Boost version: ..
-- Found the following Boost libraries:
-- system
-- log_setup
-- log
-- date_time
-- filesystem
-- thread
-- Configuring incomplete, errors occurred!

**Comment by bpvarsity** [comment]
Should I try another version of boost maybe?

**Comment by jerrymag** [comment]
Try 1.55

**Comment by bigrck64** [comment]
See my instruction for Debian7 and libboost 1.55 here: https://github.com/nicehash/nheqminer/issues/13

**Comment by bpvarsity** [comment]
@bigrck64 that fixed it! You are the man
