### ISSUE TITLE
Don't hardcode pool address

### ISSUE THREAD

**Issue by sammy007** [nicehash/nheqminer#8]
FFS. There will be a dozen useless forks with hardcoded pools in a week. Play nice, hash.

**Comment by tupieurods** [comment]
Agree.
And pretty easy to fix:
Just give an ability to control this 2 lines: https://github.com/nicehash/nheqminer/blob/master/nheqminer/main.cpp#L149-L150
No point to restrict pool just by nicehash

**Comment by asluchevskiy** [comment]
Yes, one of this forks -- mine, lol.

**Comment by nicehashdev** [comment]
nheqminer is open source; if you don't like something, you can simply fork it and create your own bins.
