### ISSUE TITLE
use 2 "gpu" threads for more performance

### ISSUE THREAD

**Issue by marienuac** [nicehash/nheqminer#88]
all the other miners do it and reach twice the hashrate. current work around for nheqminer is to run 2x nheqminer.exe to reach similar performance but this is a gimmik and very unreliable at times.

**Comment by chronosek** [comment]
i have i7-4790k@4.6 it have 4cores/8threads
- nheqminer 6 threads - 24 sol/s
- 2x nheqminer 2 threads - 22 sol/s
- nheqminer 6 threads but affinity for 7 cores (and gpu on 8th) - 28 sol/s from cpu

**Comment by marienuac** [comment]
i meant gpu threads

running 2 miners aka two nheqminer.exe's give more performance

**Comment by chronosek** [comment]
On gtx980 
1x nheqminer - 100% load, 32% fb usage, 62% power usage - 25 sol/s
2x nheqminer - 100% load, 40% fb usage, 62% power usage - 25 sol/s
