### ISSUE TITLE
fasm: sh assemble.sh error: out of memory

### ISSUE THREAD

**Issue by lpvm** [nicehash/nheqminer#95]
sh assemble.sh returns 
```
# sh assemble.sh 
flat assembler  version 1.71.57  (16384 kilobytes memory)
error: out of memory.
flat assembler  version 1.71.57  (16384 kilobytes memory)
error: out of memory.
```
It's run in a docker image.
What to do?

**Comment by buzztiaan** [comment]
add -m1024583 behind 'fasm' in the sh script

**Comment by lpvm** [comment]
You mean in between `fasm` and `equihash_avx{1,2}.asm`
It works, thank you for your fast answer!
