### ISSUE TITLE
Where is /Linux_cmake/nheqminer_cpu ?

### ISSUE THREAD

**Issue by lpvm** [nicehash/nheqminer#96]
As per the instructions to install on Linux:

`cd nheqminer/cpu_xenoncat/Linux/asm/ && sh assemble.sh && cd ../../../Linux_cmake/nheqminer_cpu && cmake . && make`

I have no `/Linux_cmake/`, not even a file named `nheqminer_cpu`.  My fault or have things changed?  What to do then?

**Comment by sebastianst** [comment]
I do have these files. Are you on the `Linux` branch?

**Comment by S74nk0** [comment]
new commits have it... on master and Linux branches
