### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by PwnK** [nicehash/nheqminer#97]
Error	1	error LNK1181: cannot open input file 'cpu_tromp_AVX.lib'
I'm using Visual studio 2013.

**Comment by S74nk0** [comment]
Check the **Solution Configuration** and build with Release and ReleaseSSE2. This is probably the problem. Report back if that is the case

**Comment by chronosek** [comment]
for me works that: change to ReleaseSS2. build only cpu_tromp, change to Release without cleaning, build nheqminer

**Comment by PwnK** [comment]
Thanks that fixed the issue. That happened because i only tried building with ReleaseSSE2.
